### PR TITLE
Fix absence of spaces in the text.

### PR DESCRIPTION
**Pull request by Maximys**
Fixes #

### Context
Absence of spaces in the some output messages.

### Changes Made
Added necessary spaces

### CODE REVIEW

**Comment by gundermanc** [comment]
> @gundermanc, Maximys noticed that some of our translations are missing spaces. I assumed the originals in our strings.resx would similarly be missing spaces, but they aren't. Is a PR like this the right way to fix that? And is there something we should do going forward to help prevent this?

Hello! I'm not sure what I can add here... none of the Visual Studio components I worked on ever used XLF based localization. It looks like it might be a reasonable fix.

**Comment by Forgind** [comment]
> Hello! I'm not sure what I can add here... none of the Visual Studio components I worked on ever used XLF based localization. It looks like it might be a reasonable fix.

Sorry gundermanc; I pinged the wrong person. I meant to @cristianosuzuki77

**Review by Forgind — CHANGES_REQUESTED** [review]
Thanks for bringing this to our attention @Maximys! cristianosuzuki77 told me offline that if we just take this PR, automation will come in later and undo it. He said he'd use this as a starting point to resolve it in a way that will prevent it from coming back, so I propose waiting for that rather than merging this.

**Comment by Maximys** [comment]
@Forgind ,  if I correctly understand, it'll be undo in [dotnet/dotnet](https://github.com/dotnet/dotnet/tree/d299b2cab65f78f09687dc723cfecae3c1d7f59e/src/msbuild/src/Tasks/Resources/xlf)  repository, that's why I had created PR to current repository.
May be I'm wrong

**Comment by JanKrivanek** [comment]
@Maximys thank you very much for spotting this and putting efforts into improvements!

Unfortunatelly currently there is no (easy) way how community could contribute to the localizations. Loosely related discussion on allowing community translations: https://github.com/dotnet/sdk/issues/27257 
The story around fixing the official transaltion is similar - this is currently not possible.

The translations are done by separate team and 'flown' automatically into subscribed repositories - any custom changes would be overwritten on next sync (see: https://github.com/dotnet/msbuild/pulls?q=is%3Apr+%22Localized+file+check-in+by+OneLocBuild%22)

The only way how to initiate translation change is to file a bug with localization team:
* [Internal only link - bug template] https://aka.ms/icxLocBug
* [Internal only link - feedback form] https://aka.ms/localizationfeedback 
* [External - feedback form] https://aka.ms/provide-feedback

The bar for reflecting those submissions is however currently very high - it's not guaranteed that pure translation or/and formatting issues will be reflected (beyond functional/legal/offensive concerns - which take priority)

**Pull request closed without merging**
