### PR TITLE
[WIP] Resurrect deprecated unit tests

### PR DESCRIPTION
**Pull request by SingleAccretion**
This a draft pull request that tries to "resurrect" unit tests under `src\Deprecated`: make them build and pass.

The fist commit here is a preview of what is to be done next: changing the projects to SDK-style ones, converting the unit tests to Xunit, fixing any bugs that crop up along the way.

Given the scale of the work and the status of the projects, I would very much appreciate the feedback on my approach here:
1. While trying not to bring unnecessary dependencies, I do use the `Shared` files (instead of, for example, copy-pasting the necessary bits into the `Deprecated` folder). This is not desirable (makes "freezing" the projects impossible), but this is how the actual deprecated projects are set up right now.
2. I do use explicit `Compile Include=""`s for non-shared files. I would like to drop them, but this is also for consistency with the actual deprecated projects.
3. I do convert the tests to Xunit instead of bringing in the original testing packages (MSTest and NUnit (so old it does not even exist on Nuget.org)).
4. I do try and make the tests pass. This means changing code that should probably not be touched (for example, the one fix displayed here is the result of the fact that newer frameworks perform more stringent bounds checks in `StringBuilder`).

If this work is to be determined unnecessary and/or too risky, I would advocate for straight removal of these unit tests, as in their current state they are just a dead weight on the repository, unbuildable and unusable.

cc @rainersigwald

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Correct me if I'm wrong, but the goal here seems off to me.

> This a draft pull request that tries to "resurrect" unit tests under src\Deprecated: make them build and pass.

Is this something we even want to do? I was under the assumption that anything under Deprecated was no longer relevant but needed to stay for "legacy reasons."

**Comment by SingleAccretion** [comment]
@BenVillalobos That is my understanding of the `Deprecated` folder as well. There is, however, a difference between actual source projects in that folder, which build and will presumably run somewhere somehow and unit tests, which are neither buildable nor runnable right now. So, this PR's goal is to bring them to parity.

However, I can very much see why this might not be desirable. In that case, as outlined above, I would advocate for straight removal if this dead code.

**Review by BartoszKlonowski — COMMENTED** [review]
I respect the will to improve the testing and thank you.
Thing is that if we really want to improve the unit testing, we should start with test that are up-to-date but are failing for some reason. The other thing to do could be to recognize dead tests or flaky tests and fix them/remove them.
Perhaps it's just my opinion, but it would be great to have all tests passing on main branch - it would improve the ease the development of any change.

**Comment by rainersigwald** [comment]
Since @SingleAccretion had already done the work for some testing, I said I'd be willing to turn on tests for deprecated-assembly behavior, but it wasn't a high priority. I haven't looked at the tests and changes yet, but I think it's reasonable to have tests for the deprecated assemblies--otherwise we might accidentally change their behavior in a breaking way for those who still depend on them.

I'd love to delete the whole folder! But we haven't been willing to do that yet. Maybe for the next major version.

**Comment by rainersigwald** [comment]
> it would be great to have all tests passing on main branch

@BartoszKlonowski are you seeing otherwise? We expect test runs to fail. There's a bit of flakiness we're still chasing, and if you see any please file a bug!

**Comment by SingleAccretion** [comment]
Closing as I unfortunately do not have the time to properly finish this right now.

**Pull request closed without merging**
