### PR TITLE
Move to V3 publishing

### PR DESCRIPTION
**Pull request by BenVillalobos**
### Context
V3 publishing is much faster and is required for publishing to the "VS 17.0" channel.

### Changes Made
Followed this: https://github.com/dotnet/arcade/blob/main/Documentation/CorePackages/Publishing.md#how-to-upgrade-from-v2-to-v3

Add eng\publishing.props with single propertygroup `PublishingVersion` set to 3.
Pass `publishingInfraVersion: 3` to post-build yml.

### Testing
Should launch an exp/ branch to verify this

Added `exp/bevillal/v3-publish-test` as a default channel to "VS 17.0" and kicked off a pipeline build here: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4655204&view=results

- [ ] Remove `exp/bevillal/v3-publish-test` as a default channel from "VS 17.0"

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Looks like it works: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4667988&view=results

**Comment by epananth** [comment]
The build did not kick off maestro promotion pipeline. I checked the darc get-build 
```
darc get-build --id 86878
Repository:    https://dev.azure.com/devdiv/DevDiv/_git/DotNet-msbuild-Trusted
Branch:        refs/heads/bevillal/v3-publish-test
Commit:        be418e2d9904cd12548d6b64b1a68effcf3bae8f
Build Number:  20210420.1
Date Produced: 4/19/2021 4:40 PM
Build Link:    https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4667988
BAR Build Id:  86878
Released:      False
Channels:
```
The build is using the azdo internal repo url instead of the translated github url. 

Is there any reason why we cannot get the latest from .NET Eng - Latest channel?

**Comment by BenVillalobos** [comment]
@epananth That would be pending https://github.com/dotnet/msbuild/pull/6143, as we're not on net6.0 just yet.

**Comment by BenVillalobos** [comment]
@epananth I think your concern would be solved by this PR: https://github.com/dotnet/arcade/pull/7267

**Comment by epananth** [comment]
@MattGal  is making a fix in arcade-validation to get this unblocked. I was able to test the changes he merged 

https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4677589&view=results

**Comment by epananth** [comment]
It will be good to run a test again..

**Review by epananth — APPROVED** [review]

**Comment by epananth** [comment]
Yaaay! finally :)

**Review by rainersigwald — APPROVED** [review]

**Pull request merged**
