### PR TITLE
Document opt-outs

### PR DESCRIPTION
**Pull request by Forgind**
Adds documentation for #7008

### CODE REVIEW

**Comment by rainersigwald** [comment]
Why is this a separate PR?

**Comment by Forgind** [comment]
> Why is this a separate PR?

As I recall, we talked about waiting to actually merge documentation until the code enabling them GAs since otherwise, people using 17.0 might see it and wonder why the documentation is "wrong."

**Comment by rainersigwald** [comment]
Ah, that applies to docs on the public-facing doc site (in https://github.com/MicrosoftDocs/visualstudio-docs/blob/master/docs/msbuild), but not to this repo--this repo is in the future all the time.

**Comment by Forgind** [comment]
Ok. Pushed it to the original PR.

**Comment by ghogen** [comment]
@Forgind @rainersigwald 
This is documented on the Wiki, but is it something that users would need in the main documentation at https://docs.microsoft.com/visualstudio/msbuild ?

**Comment by rainersigwald** [comment]
Yes, we should put this in normal public docs.

**Pull request closed without merging**
