### PR TITLE
use InvariantCulture with double.TryParse

### LINKED ISSUE #8798: [Bug]: Number literals are interpreted differently depending on locale
### Issue Description

Passing literals with dots and commas to property functions results in differently evaluated projects depending on locale / regional settings under which the MSBuild process runs.

### Steps to Reproduce

```xml
<Project>
  <Target Name="Build">
    <Message Text="$([MSBuild]::Add('1,2', 1))"/>
  </Target>
</Project>
```

### Expected Behavior

The `Message` task should print `13` regardless of locale.

### Actual Behavior

English/invariant: `13`

Switch **Regional format** to one that uses comma for decimal separator, for example French. The task prints `2,2`.

### Analysis

This is caused by calling the default overloads of `double.Parse` in evaluation.

Doesn't look like a recent regression but the .NET Framework-bundled MSBuild doesn't seem to have this bug.

### Versions & Configurations

MSBuild version 17.7.0-preview-23267-02+fe79798bd for .NET Framework

### PR DESCRIPTION
**Pull request by jrdodds**
Fixes #8798

### Context
Locale differences can produce different results

### Changes Made
Change to use overloads of double.TryParse() that accept an IFormatProvider

### Testing
ran unit test suite

### CODE REVIEW

**Comment by danmoseley** [comment]
Does this need a change wave as it may break builds?

Btw usually it's best to keep large formatting changes in their own PR if possible

**Comment by jrdodds** [comment]
The change is also in PR #8710 which is in a change wave.

> Btw usually it's best to keep large formatting changes in their own PR if possible

The editor auto-format on save with remove trailing space was enabled and I missed it. The changes are all whitespace at the end of a line. I'll make a commit to undo the whitespace change

**Comment by jrdodds** [comment]
The formatting changes have been reverted.

**Comment by JanKrivanek** [comment]
Is this fully superseded by #8710?
Let's see if the issue is discovered in additional places, otherwise I'd keep it just in #8710

Other than that - it looks good - just doesn't feel as in need of separate PR

**Comment by jrdodds** [comment]
PR #8710 contains all the changes that are in this PR.

**Comment by JanKrivanek** [comment]
> PR #8710 contains all the changes that are in this PR.

We've now merged #8710, should this one be closed then?

**Comment by jrdodds** [comment]
> We've now merged https://github.com/dotnet/msbuild/pull/8710, should this one be closed then?

Yes.

**Comment by JanKrivanek** [comment]
Thank you @jrdodds

**Pull request closed without merging**
