### PR TITLE
Retain properties on double DeepCopy

### PR DESCRIPTION
**Pull request by rainersigwald**
Two bugs combined to make DeepCopy on a PRE that was itself produced via DeepCopy fail:

1. The first copy made _two_ text nodes for each property-value text node because there was a single text-node child.
2. The second copy skipped copying text node values, erasing the property.

Co-Authored-By: svetkereMS <32176484+svetkereMS@users.noreply.github.com>

### CODE REVIEW

**Review by Forgind — APPROVED** [review]
Makes sense to me!

**Review by BenVillalobos — DISMISSED** [review]

**Comment by Forgind** [comment]
Still need QB/tactics approval, right?

**Comment by Forgind** [comment]
Since it sounds like this isn't the way we're going with this, close?

**Comment by BenVillalobos** [comment]
Friendly ping, there's a merge conflict here.

**Comment by rainersigwald** [comment]
I'd also like @svetkereMS to sign off on this (we're trying to fix the clone-XML-properties bug again, without regressing the double-`DeepCopy` thing this time).

**Comment by Forgind** [comment]
We haven't touched this in a long time. Finish? Get approval? Close?

**Pull request closed without merging**
