### PR TITLE
Add paragraph to documentation comment

### PR DESCRIPTION
**Pull request by elachlan**
Documentation changes from Roslynator:
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1226.md
https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1232.md

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Closing to reopen and trigger a CI build.

**Comment by BenVillalobos** [comment]
I don't feel very strongly about this change, as it doesn't help with code readability like the other refactors do. That being said I'm only opposed to how much time it would take to review the changes. Is there any way to break these into smaller PRs?

Hold off on changes with this PR since we can discuss it in our PR review meeting on Friday.

**Comment by elachlan** [comment]
> I don't feel very strongly about this change, as it doesn't help with code readability like the other refactors do. That being said I'm only opposed to how much time it would take to review the changes. Is there any way to break these into smaller PRs?
> 
> Hold off on changes with this PR since we can discuss it in our PR review meeting on Friday.

Biggest positive is that the XML comments are used in automated documentation and for code descriptions. This change makes those easier to read.

**Comment by Forgind** [comment]
Team triage:
We don't think the advantage for automated documentation is worth the code churn. If we make this a linter rule in the future, we can reopen it.

**Comment by elachlan** [comment]
> Team triage:
> We don't think the advantage for automated documentation is worth the code churn. If we make this a linter rule in the future, we can reopen it.

The difference is really when you hover over a method name in vs, its then a lot easier to read. But I understand.

**Comment by Forgind** [comment]
Thanks for understanding.

**Pull request closed without merging**
