### PR TITLE
Fix the unhandled Path.Combine exceptions

### PR DESCRIPTION
**Pull request by JaynieBai**
Fixes [#10497](https://github.com/dotnet/msbuild/issues/10497)

### Context
```xml
 <ItemGroup>
    <FileCopy Include="mytestfile.ps1">
      <DestinationFolder>"$(Output)\bin"</DestinationFolder>
    </FileCopy>
  </ItemGroup>
<Target Name="RunCopy" Inputs="@(FileCopy)" Outputs="@(FileCopy->'%(DestinationFolder)\%(Filename)%(Extension)')">
</Target>
```

Bad string input in the DestinationFolder. This makes .NET Framework Path.Combine has unhandled exceptions.
### Changes Made
Throw the project exception when the path has invalid characters.

### Testing
InvalidPathInTargetOutPuts

### CODE REVIEW

**Comment by JanKrivanek** [comment]
Can you past sample output of `dotnet build` of the project in question after this fix?

**Review by JanKrivanek — APPROVED** [review]
Looks good - thank you!

**Comment by JaynieBai** [comment]
> Can you past sample output of `dotnet build` and of `msbuild.exe` of the project in question after this fix?

For project 
 ```
<ItemGroup>
    <FileCopy Include="mytestfile.ps1">
      <DestinationFolder>"$(Output)\bin"</DestinationFolder>
    </FileCopy>
  </ItemGroup>
<Target Name="RunCopy" Inputs="@(FileCopy)" Outputs="@(FileCopy->'%(DestinationFolder)\%(Filename)%(Extension)')">
</Target>
```

dotnet build successfully
image
msbuild.exe 
image

**Comment by JanKrivanek** [comment]
> > Can you past sample output of `dotnet build` and of `msbuild.exe` of the project in question after this fix?
> 
> For project
> 
> ```
> <ItemGroup>
>    <FileCopy Include="mytestfile.ps1">
>      <DestinationFolder>"$(Output)\bin"</DestinationFolder>
>    </FileCopy>
>  </ItemGroup>
> <Target Name="RunCopy" Inputs="@(FileCopy)" Outputs="@(FileCopy->'%(DestinationFolder)\%(Filename)%(Extension)')">
> </Target>
> ```
> 
> dotnet build successfully image msbuild.exe image

This is definitely improved behavior.
I'm wondering if we can make it even more user-friendly by giving user clue where is the invalid path comming from.
It seems the code is sourcing the paths from items here:

https://github.com/dotnet/msbuild/blob/f422d8d7dfe0a7115b11b31470215ad6b7723138/src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs#L644

we should be able to extract some more diagnostic info there (e.g. project path and item type)

**Comment by JaynieBai** [comment]
> > > Can you past sample output of `dotnet build` and of `msbuild.exe` of the project in question after this fix?
> > 
> > 
> > For project
> > ```
> > <ItemGroup>
> >    <FileCopy Include="mytestfile.ps1">
> >      <DestinationFolder>"$(Output)\bin"</DestinationFolder>
> >    </FileCopy>
> >  </ItemGroup>
> > <Target Name="RunCopy" Inputs="@(FileCopy)" Outputs="@(FileCopy->'%(DestinationFolder)\%(Filename)%(Extension)')">
> > </Target>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > dotnet build successfully image msbuild.exe image
> 
> This is definitely improved behavior. I'm wondering if we can make it even more user-friendly by giving user clue where is the invalid path comming from. It seems the code is sourcing the paths from items here:
> 
> https://github.com/dotnet/msbuild/blob/f422d8d7dfe0a7115b11b31470215ad6b7723138/src/Build/BackEnd/Components/RequestBuilder/TargetUpToDateChecker.cs#L644
> 
> we should be able to extract some more diagnostic info there (e.g. project path and item type)

@JanKrivanek  What about this ouput?
image

**Review by MichalPavlik — APPROVED** [review]

**Comment by JanKrivanek** [comment]
Thank you for improving the message!

**Comment by samedder** [comment]
Kudos to everyone, love to see a quick turnaround on a relatively minor issue, but has a notable improvement in the UX.

**Pull request merged**
