### PR TITLE
Set CA1507 to Warning and fix instances of errors

### PR DESCRIPTION
**Pull request by elachlan**
Relates to #7174

### CODE REVIEW

**Review by Forgind — APPROVED** [review]

**Comment by Therzok** [comment]
Offtopic, but shouldn't these analyzers be enabled via editorconfig[editorconfig](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022) ?

**Comment by elachlan** [comment]
> Offtopic, but shouldn't these analyzers be enabled via [editorconfig](https://docs.microsoft.com/en-us/visualstudio/code-quality/use-roslyn-analyzers?view=vs-2022) ?

Yes. But the change to enable them was done prior to the vs change for editor config. We can do a PR to fix it once these latest PRs are merged.

**Comment by elachlan** [comment]
@Therzok I have added a follow up in #7174 to convert to the editorconfig. I will do a PR soon.

**Comment by elachlan** [comment]
@Therzok there is a draft PR at #7192

**Pull request merged**
