### PR TITLE
Enumerate possible values for the Nullable property

### PR DESCRIPTION
**Pull request by drewnoakes**
This XSD file controls completion of MSBuild project files in the editor. Adding these values allows completion of values for the Nullable element.

---

Corresponding VS PR: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/265087

cc: @jcouv

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Why do we need a VS PR and a github PR? If we merge this in through github it should flow into VS automatically

**Comment by jcouv** [comment]
Thanks @drewnoakes. 
There is something I still don't understand though. I see that this XSD file added "Nullable" almost a year ago, yet I didn't see a completion for "Nullable" in 16.7p5. Is that working for you?

**Comment by drewnoakes** [comment]
@BenVillalobos @jcouv, I don't know why but it seems that adding it here doesn't influence completion in VS.

For example, `Nullable` was added to this repo in #4391 on 23 May 2019, but didn't appear in the product until [AB#250249](https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/250249) on 18 Jul 2020.

> I didn't see a completion for "Nullable" in 16.7p5. Is that working for you?

I see it in VS master, so I guess it's just a timing thing.

**Comment by Forgind** [comment]
The change does not flow into VS automatically, but we have instructions on how to do it [here](https://github.com/dotnet/msbuild/blob/master/documentation/wiki/Localization.md#localizing-xsd-intellisense). The manual steps were never followed after the original PR to add nullable was merged—the author closed the issue, and it didn't reappear on our radar until we merged more xsd changes ([here](https://github.com/dotnet/msbuild/pull/5352)) and noticed there was more to merge into VS than we'd expected. If I remember correctly, the nullable xsd changes were only merged into VS master a couple weeks ago, as drewnoakes pointed out, so they won't come out until 16.8p1.

This is something I think we _should_ automate, but it isn't automated at this point. It's being tracked by [#5533](https://github.com/dotnet/msbuild/issues/5533).

**Comment by jcouv** [comment]
@Forgind @drewnoakes Thanks a lot for the clarification. I'm relieved that we understand where the flow broke. 
If it can't be automated, I would suggest adding some comments in the file as a reminder ("if you modify this file, please follow instructions provided there...").

**Comment by Forgind** [comment]
Reasonable. If you make the changes, I'll approve.

**Comment by drewnoakes** [comment]
@Forgind @BenVillalobos I don't have permission to merge this. What's the process here?

**Comment by BenVillalobos** [comment]
@drewnoakes we typically merge PRs on Fridays during our PR review meeting. This looks simple enough that we can go ahead and merge once we confirm that our pipeline builds are working again.

**Comment by BenVillalobos** [comment]
Seeing as https://github.com/dotnet/msbuild/issues/5646 hit many other PRs I'd like to close and reopen this just in case.

**Comment by drewnoakes** [comment]
@BenVillalobos would you like me to hold off merging https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/265087 until this goes in?

**Comment by BenVillalobos** [comment]
@drewnoakes My assumption is that merging the VS side first would be a non-issue, but let's play it safe. VS and this repo were out of sync previously, where this repo was "ahead" and VS "caught up". Not sure what would happen in the reverse scenario. And in the interest of not breaking things while Rainer is out, let's just have it sit for another day or two. 

Future /cc to @rainersigwald who likely knows about some one-off-random-break-because-of-an-insignificant-looking-change™ knowledge 😉

**Comment by Forgind** [comment]
@drewnoakes, I'd still wait until it's been inserted, but after that, merge away!

**Comment by drewnoakes** [comment]
@Forgind I don't know when this repo inserts.

**Comment by Forgind** [comment]
We inserted yesterday, so you're good.

**Comment by rainersigwald** [comment]
> This is something I think we _should_ automate, but it isn't automated at this point. It's being tracked by [#5533](https://github.com/dotnet/msbuild/issues/5533).

This is not true. It is automated now (#5531), _except for the release branches_. All other definitions (including the standard master->master that does almost all insertions) now automatically carry the XSD update. #5533 tracks turning it on for the release branches (which cover multiple possible servicing releases, some of which would fail with this, so I still think we should wait to do it).

@drewnoakes, because of this your completed PR was an empty commit: https://devdiv.visualstudio.com/DevDiv/_git/VS/commit/6b03868ff6ed4ad04f8d18c2443a8d8adb0e2179

**Pull request merged**
