### PR TITLE
Switch eng/common to linguist-vendored

### PR DESCRIPTION
**Pull request by rainersigwald**
This is a more accurate description of what's going on here; the code canonically lives in `dotnet/arcade` and so is [vendored](https://github.com/github/linguist/blob/master/README.md#vendored-code) here.

### CODE REVIEW

**Comment by rainersigwald** [comment]
@BenVillalobos I'd like to merge this ASAP because it will make reviewing #5836 easier :)

**Comment by BenVillalobos** [comment]
@rainersigwald this modifies PR reviews as well? I read the docs as it applying more to the stats on our repo page for languages.

**Review by BenVillalobos — APPROVED** [review]

**Comment by rainersigwald** [comment]
> this modifies PR reviews as well? I read the docs as it applying more to the stats on our repo page for languages.

That's . . . a really good question. I read it that way but maybe not? Checking now.

**Comment by rainersigwald** [comment]
Looks like we need both; see https://github.com/rainersigwald/msbuild/pull/4/files

**Comment by BenVillalobos** [comment]
LGTM. This is a cool feature, effectively hiding all irrelevant changes. I kinda wish it would highlight that better, IIRC the message `Some generated files are not rendered by default. Learn more.` looks similar to the message about how some diffs are too big . So it could easily be mistaken.

**Comment by BenVillalobos** [comment]
@rainersigwald should we consider adding `linguist-generated` to everything under `ref/`? Had this idea when looking over https://github.com/dotnet/msbuild/pull/5936. If so, should be considered "low priority quality of life change"

**Comment by BenVillalobos** [comment]
While we're at it, `src/Build/Resources/xlf` to auto-hide generated resources would be nice

**Pull request merged**
