### PR TITLE
remove #if NEVER in hashset

### PR DESCRIPTION
**Pull request by danmoseley**
This is a modified copy of Hashset and [someone ](https://github.com/danmoseley) circa 2008 figured it would be helpful to have the unused bits commented out (and indented) so as to easily diff the two. That turned out to be unnecessary.

### CODE REVIEW

**Review by ladipro — APPROVED** [review]
nit: The Originals directory is now empty, so maybe this can be removed as well?

https://github.com/dotnet/msbuild/blob/39e20dce0c00a572f1fbd20a0a520d4e941bbc33/src/Build/Microsoft.Build.csproj#L803-L805

**Comment by ladipro** [comment]
Is it still necessary to keep modified copies of BCL containers in this repo? Specifically for `RetrievableEntryHashSet`, can we get the same behavior by extending from `HashSet` or `Dictionary`?

**Comment by danmoseley** [comment]
> can we get the same behavior by extending from HashSet or Dictionary

Not that I'm aware of. Note that it's a hybrid of the two- a dictionary with the storage of a HashSet, because the key is stored on the value

**Comment by danmoseley** [comment]
> nit: The Originals directory is now empty, so maybe this can be removed as well?

fixed

**Review by YuliiaKovalova — APPROVED** [review]

**Pull request merged**
