### PR TITLE
Cleanup: Delete NGen of T

### PR DESCRIPTION
**Pull request by ladipro**
### Context

The sole purpose of introducing the type seems to have been silencing a legacy code analyzer rule. The rule does not exist anymore / has not been brought over to Roslyn (https://github.com/dotnet/roslyn-analyzers/issues/722) and it's now hurting performance, if anything. Types like `HashSet<int>` are part of the mscorlib native image and it's wasteful to duplicate the code in our binaries. The rest is handled by IBC/OptProf.

### Changes Made

Deleted NGen<T> and its uses.

### Testing

Experimental insertion to confirm no regressions.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]
For these cleanups of stale .NET Framework optimization tricks, can we wait to put them in until 17.9 codeflow is unblocked and we can get a good run with optprof to just validate that they're actually useless as we expect?

**Comment by ladipro** [comment]
Sure, this can wait. For what it's worth, there is no impact on 17.8 PerfDDRITs (tested both this change and the removal of `Pair<TKey, TValue>`).

**Review by Forgind — APPROVED** [review]

**Comment by rainersigwald** [comment]
> For these cleanups of stale .NET Framework optimization tricks, can we wait to put them in until 17.9 codeflow is unblocked and we can get a good run with optprof to just validate that they're actually useless as we expect?

We should be in good shape now.

**Comment by ladipro** [comment]
No regressions in the experimental insertion. This is good to go.

**Pull request merged**
