### PR TITLE
SA1122 Use string.Empty for empty strings

### PR DESCRIPTION
**Pull request by elachlan**
Relates to #7174
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1122.md

### CODE REVIEW

**Comment by elachlan** [comment]
Error:
`.packages/microsoft.codeanalysis.collections/4.0.0-4.21379.20/contentFiles/cs/netstandard2.0/Internal/ThrowHelper.cs(274,28): error SA1122: (NETCORE_ENGINEERING_TELEMETRY=Build) Use string.Empty for empty strings`

The issue is in microsoft.codeanalysis.collections. I am unsure how to fix it, other than fixing it upstream.

**Comment by elachlan** [comment]
@sharwell, apparently `""` is already interned by the compiler. Was the idea of SA1122 to reduce string allocations? or is the hardcoded string used for another purpose?

Based on my reading, the advantage is in readability and to reduce the chance of a hidden zero width space character.

There was acutally one disadvantage that I saw:
"Another difference is that String.Empty generates larger CIL code"
https://stackoverflow.com/a/17386465/908889

It also isn't a constant:
https://stackoverflow.com/questions/507923/why-isnt-string-empty-a-constant

Which results in some usages being incorrect:
https://stackoverflow.com/a/13703103/908889

runtime also turned down adding a constant and suggested using `""`:
https://github.com/dotnet/runtime/issues/60508

**Comment by elachlan** [comment]
@Forgind You may want to review this with the team? We can set the analyzer to none if it isn't helpful.

**Comment by elachlan** [comment]
@rainersigwald Should we just disable this rule?

**Comment by sharwell** [comment]
IMO this rule is more tedious than it's worth.

**Comment by elachlan** [comment]
If the team gives the okay, I will mark the severity for this analyzer as none.

**Comment by danmoseley** [comment]
In dotnet/runtime we prefer "" . I think string.Empty is a useless vestige.

**Review by ladipro — APPROVED** [review]

**Review by rainersigwald — APPROVED** [review]

**Pull request merged**
