### PR TITLE
Updating setting SDK resolver isRunningInVisualStudio

### PR DESCRIPTION
**Pull request by sfoslund**
Tested manually along with https://github.com/dotnet/sdk/pull/12633

### CODE REVIEW

**Comment by sfoslund** [comment]
@Forgind @BenVillalobos this change was suggested by Rainer [on teams](https://teams.microsoft.com/l/message/19:2db9948434504972b9bc70d3b3ad71e2@thread.skype/1595877822195?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&groupId=4ba7372f-2799-4677-89f0-7a1aaea3706c&parentMessageId=1595877822195&teamName=.NET%20Developer%20Experience&channelName=CLI&createdTime=1595877822195)

**Comment by BenVillalobos** [comment]
@Forgind this seems low risk and unblocks Sarah. Let's prioritize it in the PR meeting tomorrow.

**Comment by sfoslund** [comment]
> Is there any reason to keep the RunningInVisualStudio version? If not, may as well remove it.

@Forgind I'm not sure what you mean, can you clarify? This change doesn't remove anything, it just changes the way this context property is set.

**Comment by Forgind** [comment]
I was thinking of https://github.com/dotnet/msbuild/pull/5501. You wanted that so you could do the thing you just replaced, right? Was there more?

**Comment by sfoslund** [comment]
#5501 set [the groundwork for this change](https://github.com/dotnet/msbuild/pull/5501/files#diff-1ddeed86543ce72d14d78ee2997cc8eaR490) as well as added an overload for the [SDK resolver IndicateSuccess method](https://github.com/dotnet/msbuild/pull/5501/files#diff-1ddeed86543ce72d14d78ee2997cc8eaR513), so none of that can be removed.

**Pull request merged**
