### PR TITLE
Match encoding when WriteOnlyWhenDifferent is set

### LINKED ISSUE #8361: WriteOnlyWhenDifferent should check with the same encoding
The encoding is missing on the check for `WriteOnlyWhenDifferent` 
https://github.com/dotnet/msbuild/blob/56087a97257fab6a67d110a7b2c4116f707325ee/src/Tasks/FileIO/WriteLinesToFile.cs#L102 
while it's present on the subsequent write: https://github.com/dotnet/msbuild/blob/56087a97257fab6a67d110a7b2c4116f707325ee/src/Tasks/FileIO/WriteLinesToFile.cs#L121

### PR DESCRIPTION
**Pull request by stan-sz**
Fixes #8361

### CODE REVIEW

**Comment by stan-sz** [comment]
Because the code fix is trivial, I've first coded up UTs to prove it's really an issue.

**Comment by JanKrivanek** [comment]
@stan-sz do you plan to update this PR to address the failure?

**Comment by stan-sz** [comment]
Yes, though I think this PR does not capture the problem with encoding from the issue I opened.

**Comment by AR-May** [comment]
Team triage: it seems that you are not going to update the PR, so we close it. If we are wrong, feel free to reopen the PR.

**Pull request closed without merging**
