### PR TITLE
Unrevert env change and fix timing issue found originally in ProjectSystemTools

### PR DESCRIPTION
**Pull request by Forgind**
### Context
The change to filtering environment variables caused a timing issue with project system tools in which it tried to read some properties then change the set of project properties, leading to a crash. This brings back the environment variable change but with a lock to prevent that issue.

### Changes Made
Introduce a new method on PropertyDictionary to allow enumeration (and filtering) within a lock.

### Testing
Tested a related change (but not this one) with the repro, and the problem did not recur. Will try testing this one specifically as well.

Edit: Just tried with and without the second commit here. The issue reproduced without it but not with it.

### CODE REVIEW

**Comment by rainersigwald** [comment]
Promoting https://github.com/dotnet/aspnetcore/pull/42571#issuecomment-1175362086 into this PR

**Comment by Forgind** [comment]
I don't understand what's interesting about their scenario, so I don't know how to reproduce it. I can reach out to dougbu to see if we can test it.

**Comment by Forgind** [comment]
@MackinnonBuck helped me get their repro to run locally on my machine. I overwrote the binaries with this change, and the enumeration failure did not recur.

(There was an error with a file not being present to be packed, but the build took significantly longer to reach that point—the repro having failed in under five seconds—and MackinnonBuck had seen it before, so I'm assuming it's unrelated.)

**Comment by Forgind** [comment]
Note:
Blocked on metaproj logger issue.

**Pull request merged**
