### PR TITLE
More Doc fixes from #5575

### PR DESCRIPTION
**Pull request by elachlan**
More Doc fixes from #5575

### CODE REVIEW

**Comment by elachlan** [comment]
@ghogen Here is the new PR.

**Comment by elachlan** [comment]
I did not change the preprocessor directives(#IF) with comments, I am unsure how to fix those.

**Comment by mfkl** [comment]
> I did not change the preprocessor directives(#IF) with comments, I am unsure how to fix those.

I'm not sure there is anything to fix. You can't ifdef in the middle of the method comments, so if you have one of your method parameters in an ifdef, you need to ifdef the whole comment section unfortunately.

**Comment by elachlan** [comment]
> Can you comment on which suggestions you took or didn't take? I didn't see any changes to AssemblyResolution or ReferenceTable, for instance.

For AssemblyResolution and ReferenceTable the comments were directed specifically at preprocessor directives. So I didn't make those changes.

**Comment by Forgind** [comment]
https://github.com/dotnet/msbuild/pull/5575#discussion_r474836617
https://github.com/dotnet/msbuild/pull/5575#discussion_r474837451
https://github.com/dotnet/msbuild/pull/5575#discussion_r474837890

are the three other comments I noticed. Everything else looks good to me! Though I'll still tag @ghogen again.

**Comment by Forgind** [comment]
Thanks!

**Pull request merged**
