### PR TITLE
Use dotnet certificate

### PR DESCRIPTION
**Pull request by mmitche**
See https://github.com/dotnet/announcements/issues/184

### CODE REVIEW

**Comment by mmitche** [comment]
Official test https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4751767&view=results

**Comment by rainersigwald** [comment]
@BenVillalobos can you fix optprof on that build to check it out?

**Comment by BenVillalobos** [comment]
New build here: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4752063&view=results

**Comment by BenVillalobos** [comment]
I noticed
```xml
<!-- Since this repo isn't on Arcade 6, UseDotNetCertificate is not available. Do the update here instead. -->
```
We have an arcade 6 update that's ready to merge. Will updating to 6 automagically fix this for us?

**Comment by mmitche** [comment]
> I noticed
> 
> ```
> 
> ```
> 
> We have an arcade 6 update that's ready to merge. Will updating to 6 automagically fix this for us?

Just makes it simpler. Let's merge that first and then I can simplify this.

**Comment by rainersigwald** [comment]
> Let's merge that first and then I can simplify this.

👍🏻 Might be a couple of days because of internal VS branch availability stuff.

**Review by Forgind — COMMENTED** [review]
Didn't read comments first (please ignore)

**Comment by Forgind** [comment]
@mmitche, we merged the update to arcade 6 this morning. Sorry for the delay, but you should be good now.

**Comment by rainersigwald** [comment]
@mmitche We're on latest Arcade now. Can you do what you wanted (or link explanation so we can)?

**Comment by mmitche** [comment]
https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4822675&view=results

**Comment by mmitche** [comment]
Build looks good

**Comment by mmitche** [comment]
@rainersigwald Merge when ready.

**Comment by rainersigwald** [comment]
@mmitche even with the "this repo doesn't have `UseDotNetCertificate`" comment?

**Comment by mmitche** [comment]
@rainersigwald Oh cool let me switch over to using that.

**Comment by mmitche** [comment]
Attempt using other method: https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=4826873&view=results

**Review by Forgind — APPROVED** [review]

**Review by BenVillalobos — APPROVED** [review]

**Comment by mmitche** [comment]
Build looks good again.

**Comment by rainersigwald** [comment]
Yeah, that build failure is not your fault. Thanks!

**Pull request merged**
