### PR TITLE
Deprecates BuildEventArgs.ThreadId

### LINKED ISSUE #6152: Consider deleting BuildEventArgs.ThreadId
BuildEventArgs.ThreadId appears to be unused:
https://source.dot.net/#Microsoft.Build.Framework/BuildEventArgs.cs,e7fedb352ddef2cb,references

Consider deleting it to save memory and perf.

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #6152

### Context
BuildEventArgs.ThreadId doesn't seem used or particularly useful. We're thinking of deprecating it for 17.0.

### Changes Made
Return 0 for ThreadId instead of a real value.

### Notes
I changed the comment to indicate that it's deprecated. Is there another way I should indicate that? Looking through our repo, the only references to deprecated things were in comments, tests, .targets, and a single string resource.

### CODE REVIEW

**Review by BenVillalobos — CHANGES_REQUESTED** [review]
This looks like a use case for the obsolete tag, but I'm sure we'd be breaking many scenarios that warnaserr. Also add this PR to the changewaves doc.

**Comment by Forgind** [comment]
> I'm sure we'd be breaking many scenarios that warnaserr.

I think that's appropriate, though. Hopefully no one actually uses this, so it doesn't matter, but if they do, just seeing wrong results without explanation would be a bad experience. If a lot of people actually use it, we'd presumably revert this.

**Comment by BenVillalobos** [comment]
Fitting that all the failures we're seeing is directly because of the obsolete tag and erroring on a warning 😁 I think that's our proof to "silently" obsolete it.

**Comment by Forgind** [comment]
Hmm...might want to talk about design. The other option is to suppress those warnings for our uses (which I think we should keep in case someone wants to disable the change). I can bring it up in our next PR review meeting.

**Comment by Forgind** [comment]
Leaving this for 18.0

**Pull request closed without merging**
