### PR TITLE
Init of msbuild env variables document

### LINKED ISSUE #9739: [Documentation]: Document the env variable: MsBuildSkipEagerWildCardEvaluationRegexes
### Summary

Document in the wiki the usage of MsBuildSkipEagerWildCardEvaluationRegexes  env variable

### Background and Motivation

During the investigation of https://github.com/dotnet/msbuild/issues/9736 it took time to understand how it should work.  

### Proposed Feature

I was not able to find all the env variable list that are being considered during the build. A file containing all the env var list for msbuild would be very helpful 

### Alternative Designs

_No response_

### PR DESCRIPTION
**Pull request by f-alizada**
Fixes #9739

### Context
Please see the description in attached issue

### Changes Made
Added the new file in wiki, which will describe the behavior and usage of different environment variables that are being respected and used  in MSBuild. 

### Testing
Nothing to test

### Notes
Next steps would be to transfer all environment variables from https://github.com/dotnet/msbuild/blob/main/documentation/wiki/MSBuild-Tips-%26-Tricks.md to have a separate well indexed file for easy search.

### CODE REVIEW

**Comment by JanKrivanek** [comment]
Thank you for taking time to document this!!

It feels all the magic env vars should be documented on a single place - how about merging this info into https://github.com/dotnet/msbuild/blob/d68cc3ad77088e20a0ea22a61f4d718b1ed5ff19/documentation/wiki/MSBuild-Tips-%26-Tricks.md?plain=1#L15 or vice versa extracting (and linking) the Tips&Tricks Env Vars section to this doc?

**Comment by f-alizada** [comment]
> Thank you for taking time to document this!!
> 
> It feels all the magic env vars should be documented on a single place - how about merging this info into
> 
> https://github.com/dotnet/msbuild/blob/d68cc3ad77088e20a0ea22a61f4d718b1ed5ff19/documentation/wiki/MSBuild-Tips-%26-Tricks.md?plain=1#L15
> 
> or vice versa extracting (and linking) the Tips&Tricks Env Vars section to this doc?

Thank you for mentioning that! :) Actually I was planing to do that once current initiative with env variables in separate file is approved. As was mentioned in the PR description I suggest to link (as you mentioned) the MSBuild tips and tricks to this file, for proper indexing and easy search online, but of course this suggestion is open to discussion!

**Review by JanKrivanek — APPROVED** [review]

**Review by AR-May — APPROVED** [review]
Having MSBuild env variables documented in one place seems very reasonable to me for searching purposes.

**Comment by rainersigwald** [comment]
I'm not opposed to putting together a better list for our own purposes, but we need to be clear that most of the environment variables are _intentionally_ undocumented and unsupported. They're there primarily as emergency escape hatches for users who get into bad problems, and we don't test the combinations and so on.

**Pull request merged**
