### PR TITLE
Remove trailing white-space

### PR DESCRIPTION
**Pull request by elachlan**
Refactor to remove trailing white-space using Roslynator.

https://github.com/JosefPihrt/Roslynator/blob/master/docs/analyzers/RCS1037.md

### CODE REVIEW

**Comment by BenVillalobos** [comment]
@elachlan thanks for separating these PRs out based on which refactor! It makes for an easier review.

WRT what @Forgind mentioned, have you done any testing for merge conflicts? It looks like some PRs share the same updated files.

**Comment by elachlan** [comment]
> @elachlan thanks for separating these PRs out based on which refactor! It makes for an easier review.
> 
> WRT what @Forgind mentioned, have you done any testing for merge conflicts? It looks like some PRs share the same updated files.

Yes. I have just tried to do a merge or all the branches. I ran into merge conflicts.

I am happy for you to start merging the changes and if we run into issues, I can re-roll the changes in the PRs with the conflicts.

**Comment by Forgind** [comment]
I merged a few and started seeing some of the merge conflicts. I'll look again when they're gone.

**Comment by elachlan** [comment]
> I merged a few and started seeing some of the merge conflicts. I'll look again when they're gone.

I believe I have fixed them all.

**Pull request merged**
