### PR TITLE
Include error/warning count in Terminal Logger summaries

### LINKED ISSUE #9049: Include error/warning count in -tl summaries
from @baronfel in chat offline:

> should we include a count of errors in relevant places? I'm specifically thinking of the individual project build report sections (`"<projectname> <tfm> failed with errors <time>"` => `"<projectname> <tfm> failed with <count> errors <time>"`) and the final summary `"Build failed with errors in <time>"` => `"Build failed with <total_count> errors in <time>"`)
> 
> I ask because that number is a quick visual check for a repeated-build scenario, and once you get past a certain number of reported errors (a screenful) counting yourself becomes untenable.

### PR DESCRIPTION
**Pull request by AR-May**
Fixes #9049

### Context
Updated the Terminal Logger summary to include number of errors and warnings.

### Testing
Unit tests & local testing

### CODE REVIEW

**Comment by AR-May** [comment]
Some examples:
Screenshot 2024-03-25 160333
Screenshot 2024-03-25 160304
Screenshot 2024-03-25 160155

**Comment by baronfel** [comment]
I'm going to be annoying and ask if we can try to create different strings for the plural/non-plural counts - it's a minor thing but it adds to the quality feel quite a bit IMO.

In every case when we say `warning(s)` or `error(s)` we _know_ if the quantity is plural or not, so we should just pluralize the noun correctly - both on this final-build summary and on the per-project summaries.

**Review by baronfel — APPROVED** [review]
Thanks for plumbing this through! I'd love to see the pluralization of the project and build summaries adjusted per my other comment, though this is a great UX addition.

**Comment by AR-May** [comment]
> I'm going to be annoying and ask if we can try to create different strings for the plural/non-plural counts - it's a minor thing but it adds to the quality feel quite a bit IMO.
> 
> In every case when we say `warning(s)` or `error(s)` we _know_ if the quantity is plural or not, so we should just pluralize the noun correctly - both on this final-build summary and on the per-project summaries.

Well, that's not annoying at all, I asked myself the exact same question and also thought whether we should separate those cases. 

Here are my thoughts: We sure can differentiate singular and plural cases and write this message with different endings, with "s" and without, for English. But I wonder what's with the translations. In Slavic languages, for example, the situation with the endings is a bit more complicated and has more than 2 cases. So, we definitely can make it more readable for English and some other languages, but we probably cannot cover all the cases. Also, there is one message that has both errors and warnings count, so either we will need to have 4 messages for all the cases, or we need to break the sentence into quite small parts and combine them (which could break other languages which might have some other words order). So, I am hesitant to make the code rely on a particular language model.  I looked how it is done currently in the console logger and saw there one message for both cases.

**Comment by baronfel** [comment]
I'd be happy with logging a low-priority issue to make this look nicer for all of our supported languages :)

**Comment by AR-May** [comment]
> I'd be happy with logging a low-priority issue to make this look nicer for all of our supported languages :)

Sure, I will file it. My point is, that's no easy fix, we will need to research the best practices in order to figure out how to do this nice messaging properly :)

**Comment by baronfel** [comment]
TBH this is just a palce where resx-based localization sucks - GNU gettext/po files are able to pluralize quite easily :(

**Comment by AR-May** [comment]
> TBH this is just a palce where resx-based localization sucks - GNU gettext/po files are able to pluralize quite easily :(

yeah, I agree, current localization model is kind of limiting us here.

**Review by YuliiaKovalova — APPROVED** [review]

**Review by JanKrivanek — APPROVED** [review]

**Pull request merged**
