### PR TITLE
Servicing fixes for 16.10.2

### PR DESCRIPTION
**Pull request by rainersigwald**
Pulling together approved PRs #6531, #6520, and #6513 with a version bump.

### CODE REVIEW

**Comment by BenVillalobos** [comment]
Is there enough time for an `exp/` branch?

**Comment by rainersigwald** [comment]
I don't think there's a reason to prefer it over being optimistic, personally.

**Comment by bbrueckmann-codesys** [comment]
I hate to ask this, sorry about that 😢: do you have an eta when the 16.10.2 (which will be .NET 5.0.8 if I'm not misread something) will land?  

We're currently hitting https://github.com/dotnet/msbuild/issues/6493, which was apparently fixed with https://github.com/dotnet/msbuild/pull/6513.

**Comment by rainersigwald** [comment]
@bbrueckmann-codesys No public date, sorry. And the plan is that it will be in .NET SDK 3.0.302.

**Comment by eriawan** [comment]
> @bbrueckmann-codesys No public date, sorry. And the plan is that it will be in .NET SDK **3.0.302**.

Do you mean SDK **5.0.302** ?

**Comment by rainersigwald** [comment]
@eriawan I sure did. Edited to reduce future confusion. Thanks!

**Pull request merged**
