### PR TITLE
Revert initial RAR-as-a-service work

### PR DESCRIPTION
**Pull request by rainersigwald**
### Customer Impact
Visual Studio customers that have [DSL](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fvisualstudio%2Fmodeling%2Fmodeling-sdk-for-visual-studio-domain-specific-languages%3Fview%3Dvs-2019&data=02%7C01%7Craines%40microsoft.com%7C46b1b2d4889e4bcd124708d85fdebde6%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637364757604936699&sdata=9luNLStr6Q5hAN7qXgTMj5DkTHPmfvkiEe12NHrnDyA%3D&reserved=0) projects get an error because MSBuild's copy of `Microsoft.VisualStudio.Threading.dll` doesn't match Visual Studio's.

DSL error

### Testing
Tested manually.

### Risk
Low. Revert of a commit that added new dependencies but was opt-in only and not opted into anywhere.

### Code Reviewers
@mgoertz-msft

### Description of fix
This reverts commit 51a1071f8871e0c93afbaf1b2ac2c9e59c7b6491, reversing changes made to d58e2b7864627321d75b7a47850e9b80deac7db6.

This is an overkill solution to #5752. Since the new functionality isn't working, it's easier and safer to just remove it rather than juggle assembly loading.

### CODE REVIEW

**Comment by ladipro** [comment]
Would reverting only the change in VS setup files (src/Package/MSBuild.VSSetup/files.swr?) be enough to work around #5752? Understood that reverting everything is easier but it means non-trivial future effort to re-apply and re-review all of this again.

**Comment by rainersigwald** [comment]
I believe it would. I slightly prefer this because it avoids shipping the new assemblies to .NET SDK 5.0.100 as well as VS (a size reduction there), and is less likely to break at runtime because of missing dependencies (though that shouldn't be a real scenario anyway). Let's discuss today in bug triage.

**Comment by rainersigwald** [comment]
Team triage: let's go with #5762.

**Comment by rainersigwald** [comment]
Because the new dependencies caused SDK/installer failures (https://github.com/dotnet/installer/pull/8725#issuecomment-703798355), this now seems like a better tactical approach than #5762.

**Review by mgoertz-msft — APPROVED** [review]
MSBuild.VSSetup/files.swr changes look good to me. Can't speak about the rest though.
Thank you!

**Comment by rainersigwald** [comment]
Pushed a rebase over the loc PR that conflicted. Resolved conflicts by reverting the xlfs and running a build locally. Will merge on green.

**Review by Forgind — APPROVED** [review]

**Comment by sfoslund** [comment]
@rainersigwald is this ready to go in?

**Comment by sfoslund** [comment]
@rainersigwald will this flow to master automatically? We need it to unblock https://github.com/dotnet/installer/pull/8725

**Comment by rainersigwald** [comment]
@sfoslund that merge is in flight in #5782

**Pull request merged**
