### PR TITLE
Reintroduce FNV hashing

### PR DESCRIPTION
**Pull request by JanKrivanek**
Fixes: #9519, #7131

### Context
Contains changes from:
* Commit 1: https://github.com/dotnet/msbuild/pull/9387 (it was later reverted - https://github.com/dotnet/msbuild/pull/9520 - so first commit is reversal of that change)
* Commit 2: https://github.com/dotnet/msbuild/pull/9489
* Following commit(s): And change supporting choosing the hashing via an optional intrinsic function param.

### Usage

```
<!-- Works unchanged. Identical to [MSBuild]::StableStringHash($x, 'Legacy') -->
[MSBuild]::StableStringHash($x)

<!-- 
  $hashAlgo will currently allow:
    'Legacy' - the legacy behavior (mimicking string.GetHashCode)
    'Fnv1a32bit' - Fawler-Noll-Vo 1a 32bit
    'Fnv1a32bitFast' - Custom, faster, Fawler-Noll-Vo 1a 32bit
    'Fnv1a64bit' - Fawler-Noll-Vo 1a 64bit
    'Fnv1a64bitFast' -  Custom, faster, Fawler-Noll-Vo 1a 64bit
    'Sha256' - hex string of the Sha256 hash of the given string
-->
[MSBuild]::StableStringHash($x, $hashAlgo)
```

### Testing
* Existing test on colissions extended for all overloads
* Added test on expected output types

### Documentation

Once PR content is agreed I'll create Doc bug + PR to update https://learn.microsoft.com/en-us/visualstudio/msbuild/property-functions?view=vs-2022#msbuild-stablestringhash
We might not possibly document all the supported algos as of now.

### CODE REVIEW

**Comment by JanKrivanek** [comment]
FYI @KirillOsenkov - this is using the faster versions of FNV from MSBuildStructuredLog (the source and your meassurements are linked in the code)

**Review by AR-May — APPROVED** [review]
LGTM. 
Should we document this new feature somewhere?

**Review by f-alizada — APPROVED** [review]
LGTM! 
Asking out of curiocity: Is there anything additionally that needs to be done in binarylog viewer after this is merged?

**Comment by JanKrivanek** [comment]
> LGTM! Asking out of curiocity: Is there anything additionally that needs to be done in binarylog viewer after this is merged?

Good question.
As a rule of thumb - Viewer needs changes when there is an addition of new derivative of BuildEventArgs or a change in definition of any existing derivatives of BuildEventArgs.
In this case we are adding property function overloads - this will not have any impact on BuildEventArgs

**Pull request merged**
