### PR TITLE
[FancyLogger] -> LiveLogger

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #

### Context
~FancyLogger~ LiveLogger is the new console logger for MSBuild. The name LiveLogger better describes its functionality.

### Changes Made
- Renamed FancyLogger and helper classes to LiveLogger
- Added `/ll` and `/livelogger` command line switches to access the new LiveLogger
- Added `$MSBUILDLIVELOGGER` environment variable to acces the new LiveLogger

### Notes
All references to FancyLogger have been replaced. However, the `/flg` and `/fancylogger` command line switches remain.

### CODE REVIEW

**Review by Forgind — CHANGES_REQUESTED** [review]
It looks like GitHub is correct here in that the merge put the FancyLogger files back. Specifically, check out src\MSBuild\FancyLogger\*.

I seem to recall moving to that directory was intentional, so I'm guessing we should just move these over there and delete the FancyLogger files.

**Comment by rainersigwald** [comment]
I'm making a couple of refactors to this.

**Comment by rainersigwald** [comment]
Actually no, we'll need to go back further.

**Review by rainersigwald — COMMENTED** [review]
Ok should be ready for review now. I did basically the same things but simplified the names, and changed some of the cli-argument-parsing stuff.

**Review by Forgind — CHANGES_REQUESTED** [review]
I kinda prefer the more descriptive "LiveLoggerProjectNode"-style names unless we're actually likely to reuse any of them, and honestly, if we reuse something, and it's internal, we can rename it then. I'm not blocking on that, but that's my vote.

I am blocking on the src\MSBuild\FancyLogger\FancyLogger.cs --> src\MSBuild\LiveLogger\FancyLogger.cs part. The file shouldn't be named FancyLogger.cs.

**Comment by rainersigwald** [comment]
> I kinda prefer the more descriptive "LiveLoggerProjectNode"-style names unless we're actually likely to reuse any of them, and honestly, if we reuse something, and it's internal, we can rename it then. I'm not blocking on that, but that's my vote.

The disambiguation is in the namespace and IMO does not serve a purpose in the class name.

> I am blocking on the src\MSBuild\FancyLogger\FancyLogger.cs --> src\MSBuild\LiveLogger\FancyLogger.cs part. The file shouldn't be named FancyLogger.cs.

🤦🏻

**Comment by Forgind** [comment]
This is the experience I don't like:
image

I often search for things with ctrl-t, and if I look for things related to Project, and ProjectNode shows up, I'd assume that's related until I look to the right and notice it's in a weird path. Just trying to save myself some headache 🙂

(Granted, it happens to be far enough down currently that I wouldn't notice it, but it's still there—and on top if I search for ProjectN.)

The last three places I see FancyLogger are comments (which you may not care about), documentation\fancylogger\Opt-In-Mechanism.md (which I think should be updated), and https://github.com/dotnet/msbuild/pull/8356/files#diff-a0455d9446db624e81fedafd35e83bb7743f56419a2362a1a05dbc81dc84548bL11 along with its references.

**Comment by edvilme** [comment]
Just updated the documentation to reflect the new name. I agree it should be updated overall, will look into that in the future ;)

> The last three places I see FancyLogger are comments (which you may not care about), documentation\fancylogger\Opt-In-Mechanism.md (which I think should be updated), and https://github.com/dotnet/msbuild/pull/8356/files#diff-a0455d9446db624e81fedafd35e83bb7743f56419a2362a1a05dbc81dc84548bL11 along with its references.

**Comment by edvilme** [comment]
My bad. Updated it :D
I am working from a Mac, so that's why the .DS_Store files are added. If it is okay, I will create a PR to include .DS_Store in the .gitignore

**Comment by Forgind** [comment]
You're good 🙂

I'm fine with it being in the .gitignore; you can also disable it for yourself with:
defaults write com.apple.desktopservices DSDontWriteNetworkStores true

**Comment by edvilme** [comment]
This is a life changer, thanks! I will add it later still for any other contributors using Mac.

**Review by rainersigwald — APPROVED** [review]

**Comment by Forgind** [comment]
@rainersigwald, edvilme only addressed one part of https://github.com/dotnet/msbuild/pull/8356#issuecomment-1409470842. This isn't ready to go in.

**Review by Forgind — APPROVED** [review]

**Pull request merged**
