### PR TITLE
adjust XmlReader.Create to passed path with potentially invalid character

### LINKED ISSUE #8972: Audit/Fix code issues with localized characters in paths
### Motivation

Prevent unexpected crashes or/and build issues with hard to investigate rootcauses in localized environments

### Context

https://github.com/dotnet/msbuild/pull/8931 fixed one instance of issue with build issues caused by usage of localized characters in OS paths.
Rootcause was in passing a string path argument to `XmlReader.Create`, that expect a path URI - so either the string argument would need to be edited to form a proper URI (e.g. prepending `file://` prefix), or a stream would need to be passed to `XmlReader.Create`. The second approach was used (as it doesn't need to differentiate what the proper [uri schema](https://en.wikipedia.org/wiki/List_of_URI_schemes) should be)
However there are other possible buggy usages in the code: https://github.com/search?q=repo%3Adotnet%2Fmsbuild%20XmlReader.Create&type=code
Plus there might be other similar APIs accepting string argument, converting it internaly into uri - specifically in `System.Xml` namespace (e.g. [`XPathDocument` ctor](https://learn.microsoft.com/en-us/dotnet/api/system.xml.xpath.xpathdocument.-ctor?view=net-7.0#system-xml-xpath-xpathdocument-ctor(system-string)) - we are not using this one specifically - but just for ilustration)

### Suggested Approach

Traverse [`XmlReader.Create` usages](https://github.com/search?q=repo%3Adotnet%2Fmsbuild%20XmlReader.Create&type=code) and fix the ones using `string` argument and replace with `Stream` arg.
Traverse other usages of `System.Xml` namespace (there will be lot - try to somehow filter/pick constructors/factories accepting string arguments representing paths) and decide whether fixing is needed as well

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Fixes #8972

### Context
https://github.com/dotnet/msbuild/pull/8931 fixed one instance of the issue with build issues caused by localized characters in OS paths.
This PR attempts to address the rest of the same unintended string -> uri conversion

### Changes Made
Passing Stream to XmlReader.Create instead of path in order to prevent unintended string -> uri conversion

### Testing
N/A

### CODE REVIEW

**Review by JanKrivanek — APPROVED** [review]
Thanks!
Looks good!

**Review by rainersigwald — APPROVED** [review]

**Review by ericstj — COMMENTED** [review]
LGTM; @karelz @MihaZupan here's a place where folks are working around URI's escaping of these characters.

**Comment by JanKrivanek** [comment]
> LGTM; @karelz Karel Zikmund FTE @MihaZupan Miha Zupan FTE here's a place where folks are working around URI's escaping of these characters.

We've already discussed this use-case with @karelz when working on #8931

**Pull request merged**
