### PR TITLE
Cleanup no-op DependsOn and missing semiciolon in common targets

### PR DESCRIPTION
**Pull request by JanKrivanek**
### Context

Extraction of nonfunctional changes from https://github.com/dotnet/msbuild/pull/10122

The removed definitions have no effect and hence can be safely removed

### CODE REVIEW

**Review by YuliiaKovalova — APPROVED** [review]

**Comment by Forgind** [comment]
How did you prove that these are all no-ops? They look like they're unsetting DependsOnTargets for various Targets, which is an op as long as it had had a value before.

**Comment by JanKrivanek** [comment]
> How did you prove that these are all no-ops? They look like they're unsetting DependsOnTargets for various Targets, which is an op as long as it had had a value before.

Good point - lm go and keep just the self assigns

**Comment by JanKrivanek** [comment]
Did a force update of this one. Now it should hopefuly have only realy wanted changes - thoughts @rainersigwald?

**Review by Forgind — APPROVED** [review]
LGTM!

**Pull request merged**
