### PR TITLE
SA1006 A C# preprocessor-type keyword is preceded by space.

### PR DESCRIPTION
**Pull request by elachlan**
Relates to #7174
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1006.md

### CODE REVIEW

**Review by sharwell — APPROVED** [review]
💡 Consider increasing SA1006 to warning as part of this pull request

**Review by Forgind — APPROVED** [review]

**Comment by Forgind** [comment]
> 💡 Consider increasing SA1006 to warning as part of this pull request

I was assuming all this would happen with rebasing on #7192, right?

**Comment by elachlan** [comment]
> > 💡 Consider increasing SA1006 to warning as part of this pull request
> 
> I was assuming all this would happen with rebasing on #7192, right?

Yes, pretty much. That would be ideal.

**Comment by elachlan** [comment]
Only changes are to deprecated code. Closing PR.

**Pull request closed without merging**
