### PR TITLE
Update 17.2 from 17.0

### PR DESCRIPTION
**Pull request by Forgind**
Brings changes to the 17.0 branch into 17.2.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]

**Comment by Forgind** [comment]
Note: merge, not squash

**Comment by Forgind** [comment]
The only reference to NetCore1ESPool-Public seems to be in source-build.yml; can you explain how that's connected to azp not running? I also see a lot of NetCore1ESPool-Internal, so do you just mean switching Public to Internal there?

**Comment by rainersigwald** [comment]
> The only reference to NetCore1ESPool-Public seems to be in source-build.yml; can you explain how that's connected to azp not running?

Sure! One of the first things Azure DevOps does when trying to start a job is parse its definition, including expanding all of the "templates" that go into it. `source-build.yml` is referenced by our PR build definition here:

https://github.com/dotnet/msbuild/blob/038f9bae9b34d1cca653360a46c5ce1eba4c2ac8/.vsts-dotnet-ci.yml#L231-L235

So it gets pulled into that. The next thing AzDO does is try to find all the pools referenced by the different jobs, so it can start finding machines to execute on. That step fails, producing errors like the one here https://dev.azure.com/dnceng-public/public/_build/results?buildId=72153&view=results

> `The pipeline is not valid. Could not find a pool with name NetCore1ESPool-Public. The pool does not exist or has not been authorized for use. For authorization details, refer to https://aka.ms/yamlauthz.`

That error can happen for two reasons, that it kinda hints at: either the pool really doesn't exist, or the pipeline doesn't have authorization to use it. In this case, it's the former, because the pool names changed because of some policy stuff that we were told about via email.

> I also see a lot of NetCore1ESPool-Internal, so do you just mean switching Public to Internal there?

I do not! We should follow the migration guidance, but in this case the file is in `eng/common/` and owned by Arcade, so as I mentioned I suspect taking an Arcade update in the `vs17.2` branch is likely the best path.

**Comment by Forgind** [comment]
That was a great explanation, thanks! I'll probably refer back to this at some point.

And it looks like you were spot on with the arcade update. I triggered an arcade update (and set darc up to check for arcade updates for 17.2 on a regular basis), and it did indeed change the pool (among other changes) and not to NetCore1ESPool-Internal. I imagine we can merge the arcade update, then pull it into this PR, and we'll be good.

**Pull request merged**
