### PR TITLE
Add support for per request input/output results cache files

### LINKED ISSUE #7112: Unable to have static-graph + isolated build + caching + // builds, working together
Hey, this is a followup of #7110

So, I'm trying to create a build server that would be responsible to maintain the compilation of a "solution" or a group of C# projects as efficiently as possible by coupling:
- static graph
- isolated builds
- caching of results
- parallelized builds

I have also tried to play around `ProjectCachePlugin` to cover some of these aspects, but I'm hitting a restriction in the design of the caching that I'm not sure how to solve.

The main problem I have is `parallelized builds` in conjunction with the others.

Let's take an example. I have this project dependencies:

- ProjRoot
  - LibA
    - LibLeaf
  - LibB
    - LibLeaf
  - LibC
    - LibLeaf

I would expect to issue a build + caching like this:

- Build LibLeaf => store cache results `LibLeaf.cache`
- Build LibA / LibB / LibC concurrently in isolate builds, with `LibLeaf.cache` input. Each build would produce `LibA.cache`, `LibB.cache`, `LibC.cache`
- Build ProjRoot in isolate builds, don't cache the output, but use the cache from `LibA.cache`, `LibB.cache`, `LibC.cache`

The server would handle the caching state, would handle the life-sync with source on the disks (e.g like [up-to-date-check](https://github.com/dotnet/project-system/blob/main/docs/up-to-date-check.md) of VS) with the ultimate benefits that builds could be much faster than even VS today because all the results are cached, so changing one project would not require to recompute the results of project dependencies...

From some [early results](https://twitter.com/xoofx/status/1466082683889586177) from the prototype I did with the existing isolate caching, it can speed up the build on a single csproj by e.g x10 times faster. It's a lot. Extend that to an entire graph and it could be a game changer.

But I have hit the limitation that I didn't fully understood in the [static-graph](https://github.com/dotnet/msbuild/blob/main/documentation/specs/static-graph.md) doc which is that isolate + cache can only happen in a `BuildManager` and the input and output cache is only setup-able per `BeginBuild`/`EndBuild`

It means that I can calculate all the above, only sequentially and single threaded, which is super limited.

So, instead, I have been trying to schedule the graph myself, by handling the scheduling similar to static-graph (so I copied the code [here](https://github.com/xoofx/BenchBuild/blob/59464264d09939c9a7a50d0d378524dbc65ce746/BenchBuild/Builder.cs#L192-L294)), I have added a way to serialize the results to disk ([here](https://github.com/xoofx/BenchBuild/blob/59464264d09939c9a7a50d0d378524dbc65ce746/BenchBuild/Builder.cs#L278)) and thought that I could rely on [project-cache](https://github.com/dotnet/msbuild/blob/main/documentation/specs/project-cache.md) through `ProjectCachePlugin` to load these serialized results.

Unfortunately, I discovered that `ProjectCachePlugin`  are also only supported in the `BuildManager` scenario, which makes them useless in a parallel build.

I would have hoped that I could have issued builds by attaching the input/output to a request (instead of Begin/EndBuild), and that it could execute on msbuild Nodes instead.

```c#
buildManager.BeginBuild();

// Iterate on projects per group in // (as it is done in static-graph scheduling
// ....
loop on batch-able groups {
  loop on project on group {
     var request = new BuildRequestData(...);
     request.Inputs = ...;
     request.OuputCache = ....;
     buildManager.Execute(submission);
     var submission = buildManager.PendBuildRequest(request);
     submission.ScheduleAsync(...);
  }
}
buildManager.EndBuild();
```

The only solution I see is to build my own kind of build server nodes to do that, by hosting a `BuildManager` and performing my own input/output in these nodes... but ouch, that's a bit more work than expected...

Side notes: the current input/output caches load is super limited in a server by only providing file path loading, while I could also maintain a memory cache that could speed things further.

Thoughts?

cc: @rainersigwald

### PR DESCRIPTION
**Pull request by xoofx**
Fixes #7112

### Context

This is a draft PR attempt to bring support for Input/Output ResultsCache file per BuildRequest so that they could be parallelized and used from msbuild nodes.

This is mainly for discussion. I made the changes without knowing much of all the consequences and internals of msbuild, so it might not be the right changes to do. 

The new API additions allow to:

1. Schedule selectively a part of a graph (a single project, all projects below a project, all projects referencing a project): This is important for developing life sync (e.g if ProjectA -> ProjectB -> ProjectC, and ProjectB is changed, we want to be able to schedule ProjectB transitively with ProjectA)
2. Setup input and output cache results per request, allow to map a ProjectGraphNode to a file path on the disk (via `GraphBuildRequestData.GraphBuildCacheFilePath`)

This PR allows to create `BuildManager` stateful clients that could efficiently handle caches of msbuild input/output files.

The performance measured can be dramatic. On 100 interdependent C# projects:

1. Building all projects, clean build
   - With this PR: 1.5s to 2s
   - With a stock VS/msbuild: 8s+
2. Rebuilding only the root project that references the 99 C# projects
   - With this PR: 150ms
   - With a stock VS/msbuild: 1.5s

This can represent a **3x to 10x speedup in build times** depending on the structure of a solution.

### Changes Made

- Add `BuildRequest.InputResultsCacheFiles` / `BuildRequest.OutputResultsCacheFile`
- Allow the `BuildRequestEngine` to load and save the cache
- Add a new constructor `GraphBuildRequestData`  + properties to schedule graph with nodes that can be executed 
  - Only the node itself
  - All the nodes below
  - All the nodes above 
- Allow caching of individual request by having a delegate `GraphBuildRequestData.GraphBuildCacheFilePath`
- Modify `BuildManager` to take into account new features of `GraphBuildRequestData`

### Testing

Local testing only with the [BenchBuild](https://github.com/xoofx/BenchBuild) project for now.
It is validating the usage of the API (build all nodes, only root, or leaf and upward) and it shows the performance benefits.

### CODE REVIEW

**Comment by xoofx** [comment]
> And it seems that they are never cleared (apart on shutdown), so I'm a bit confused how this is working with GetMatchingConfiguration if a new request on a similar config, how does it replace the previous one?
> (Ok, overall, I'm not sure I have fully understood the logic with configurations 😅 . It seems that they need to be driven by the BuildManager all the way down to nodes, but I'm not completely sure about the details)

After thinking a bit more, I think I have over complicated my solution, and I can actually use the same cache and avoid entirely the whole dance of IConfigCache. It is likely also that I need to bring the `BuildManager` code invocation I have on BenchBuild to this PR to actually handle this more gracefully from BuildManager itself.

Let's see if I can come up with something simpler.

**Comment by xoofx** [comment]
I have added a new method `BuildManager.LoadCachedResults` in order to restart a server from existing caches on disks

**Comment by xoofx** [comment]
The last commit dba134e is fixing what I think is an invalid behavior when building graph, as we should not try to build dependent projects on a project that actually failed.

**Comment by xoofx** [comment]
Hey @rainersigwald, starting to revive this old PR to discuss about the changes.

**Comment by xoofx** [comment]
I haven't checked the existing tests regarding the static graph/caching, but let me know if you have any guidance where I could add them.

**Comment by rainersigwald** [comment]
We've let this sit for too long. Closing, since it'll need to be reevaluated in the context of other cache-plugin changes.

**Comment by KirillOsenkov** [comment]
I think we need to provide @xoofx a concrete path forward here. A lot of work went into this. They have a valid need and are one of the early adopters of the static graph and caching.

Perhaps @AndyGerlicher team would have some capacity to look into this and see if a change similar to this can be seen to completion?

What are the suggested next steps for @xoofx?

**Pull request closed without merging**
