### PR TITLE
Increase ProjectRootElementCache MRU cache

### PR DESCRIPTION
**Pull request by rainersigwald**
The average imports/project in a recent OrchardCore solution
(primarily ASP.NET Core) is 83, so one project can by itself
evict stuff from the old cache of size 50.

There are likely further improvements to be made in this area
(some ideas in #6715), but increasing the size to 200 seems to
be a [significant improvement with an extremely small change](https://github.com/dotnet/msbuild/issues/6715#issuecomment-905788648).

### CODE REVIEW

**Comment by ladipro** [comment]
I agree with the above. `MSBUILDPROJECTROOTELEMENTCACHESIZE` can still be used to override the default value in the unlikely case that the change breaks someone.

**Comment by rainersigwald** [comment]
Internal perf checks are being pretty cranky and I'm still waiting on them before undrafting this:

https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/347343

**Comment by rainersigwald** [comment]
Flakiness continues but I'm going to go ahead and undraft this anyway.

**Comment by danmoseley** [comment]
Just noting that the searching that happens on import in here is O(n) scan of a linked list. You might want to keep an eye out for if that shows up in profiles now. I'm guessing not, especially since most builds won't approach 200.

**Review by ladipro — APPROVED** [review]

**Comment by rainersigwald** [comment]
> Just noting that the searching that happens on import in here is O(n) scan of a linked list. You might want to keep an eye out for if that shows up in profiles now. I'm guessing not, especially since most builds won't approach 200.

I talked about this with @rokonec and he didn't observe any problems, but we will keep an eye out. I think a more extensive fix to #6715 will be able to alleviate both.

**Comment by Forgind** [comment]
Maybe a dumb question, but why keep it as a LinkedList at all? When we're adding something to the cache, we have to check equality for everything in the cache. I have trouble imagining that's faster than a single lookup in a HashSet, even if the cache only has ~30 items in it. It would also simplify our logic somewhat, since we could just add to it and assume any duplication is taken care of. We can optionally decide if we want to keep the max size, though I don't think that'll be a big deal if we don't expect there to be 200 items anyway. I don't see anywhere we really use the order.

**Comment by danmoseley** [comment]
>  I'm not convinced it's really helpful if the cache is still bigger than we really expect it to need to be...

The typical upper bound on reused imported files is surely below 200, but that has little bearing on how many files the cache will encounter. AFAICR, there is generally one ProjectRootElementCache per process/app domain, so when you build a large tree, then the cache will reach whatever limit you set (which is OK) and then all subsequent project files will be pushed into the cache as they're encountered, and it's important that those are evicted first when more files come in.

For example, when building dotnet/runtime src\libraries, it will load 856 files, probably only 50 are reused and those must not drop from the cache. To achieve that you need some kind of ordering, which was achieved by using a LinkedList and boosting.

**Comment by Forgind** [comment]
Gotcha. A HashSet with no max would probably still perform ok from a time perspective but would keep a lot of extra stuff. If I were to recommend a data structure that maintains orderings but also provides fast lookups/removes and, even better, can be optimized to put recently touched things near the top, I'd recommend a treap (with some kind of time stamp for the heap invariant) or a splay tree. Almost certainly overkill, but I'd be happy to implement one of those for this case if you think it would help 🙂

**Comment by danmoseley** [comment]
> A HashSet with no max would probably still perform ok from a time perspective but would keep a lot of extra stuff. 

It's important that MSBuilld holds essentially zero state per project otherwise sufficiently large builds would regularly crash (32 bit) or bog down paging (64 bit). That's why we even page out build results to disk [if needed](https://github.com/dotnet/msbuild/blob/2e88dc487e73be1ed29a9b77f063250e42bfed73/src/Build/BackEnd/Components/BuildRequestEngine/BuildRequestEngine.cs#L834)

Yes, you're right there may be better data structures to achieve these semantics. 😄

**Pull request merged**
