### PR TITLE
Fail Restore when an SDK is unresolved or entry target does not exist

### LINKED ISSUE #6281: dotnet restore fails, but reports success
Copied from issue https://github.com/NuGet/Home/issues/10606 per jeffkl's guidance

## Details about Problem

Cross posting from dotnet sdk, as it isn't clear if this issue is in the sdk or the nuget client used in that sdk.
Repro posted on https://github.com/dotnet/sdk/issues/16031#issuecomment-786748923

Product version: 

dotnetsdk 3.1.406

## Repro steps and/or sample project

Repro is simple. Try to restore a package that doesnt exist. E.g. Microsoft.Build.Traversal2

```
aaronla@aaronla-rabbit:MyRepo$ dotnet restore
X:\MyRepo\dirs.proj : error : Unable to find package Microsoft.Build.Traversal with version (= 2.999.1)
X:\MyRepo\dirs.proj : error :   - Found 24 version(s) in MyCustomFeedOne [ Nearest version: 3.0.0 ]
X:\MyRepo\dirs.proj : error :   - Found 0 version(s) in MyCustomFeedTwo

aaronla@aaronla-rabbit:MyRepo$ echo %ERRORLEVEL%
0
```

### PR DESCRIPTION
**Pull request by jeffkl**
Fixes #6281

### Context
`BuildRequestDataFlags` and `ProjectLoadSettings` are set during `/t:restore` in a best effort to run the Restore target in hopes that it will correct the potentially bad state that a project is in.  Visual Studio also sets `ProjectLoadSettings.IgnoreMissingImports` so that an unresolved MSBuild project SDK doesn't prevent loading of a bad project so it can give the user an error and let them edit the file.

However, this means that from the command-line an unresolved SDK doesn't fail `/t:restore`.  This is because the missing "import" is ignored and non-existent targets are ignored so the build succeeds.

### Changes Made
Introduced two new `BuildRequestDataFlags`:

* `SkipNonexistentNonTopLevelTargets` - A new flag to be used in this context to tell the build to ignore non-existent targets but not top level ones.  In this case we're specifying `/t:restore` so if the Restore target doesn't exist, that should be an error.  Only other targets that are trying to run are ignored (like InitialTargets, Before/AfterTargets, etc).
* `FailOnUnresolvedSdk` - We still need to ignore missing imports and I can't introduce a new flag to split the implementation now since Visual Studio sets `ProjectLoadSettings.IgnoreMissingImports` as a way to ignore unresolved SDKs.  So this flag tells the evaluator to fail on an unresolved SDK but to continue ignoring other missing imports.

### Testing
Added three new unit tests:
* Restore fails when an SDK can't be resolved
* Restore fails if a top-level target like Restore doesn't exist
* Restore succeeds if a non-top-level target doesn't exist

### CODE REVIEW

**Review by Forgind — APPROVED** [review]
Looks good! Seems like there was no easy way to pass the entrypoint target(s) through to here?

**Comment by jeffkl** [comment]
@Forgind 
> Seems like there was no easy way to pass the entrypoint target(s) through to here?

Sort of, in this context `entry.Request.Targets` represents the top level target(s) to be executed based on the command-line based build:

https://github.com/dotnet/msbuild/blob/dd7831c03cc4d668fdd432d65a75087cf88a388e/src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs#L152

Which is why I'm checking if the target that doesn't exist is in that list, this tells us if a top level target isn't there which should fail the build in this context.  Other targets like InitialTargets and Before/AfterTargets to be built are [passed in](https://github.com/dotnet/msbuild/blob/dd7831c03cc4d668fdd432d65a75087cf88a388e/src/Build/BackEnd/Components/RequestBuilder/TargetBuilder.cs#L100) as `targetNames` by [the RequestBuilder](https://github.com/dotnet/msbuild/blob/073022eb44eb1664eb1c35055b4f5ed377f09706/src/Build/BackEnd/Components/RequestBuilder/RequestBuilder.cs#L1157) which handles figuring that out.

So the original `entry.Request.Targets` represents the "entry" targets or "top level" targets.

**Comment by Forgind** [comment]
Oh, I think I misunderstood that part, then. So did you add the new BuildRequestDataFlag in case that part fails? Looking more closely at it, it seems to log a message if (a particular target isn't in the list and the SkipNonexistentTopLevelTargets flag is set) or (the target is missing, and another flag is set). Otherwise, it adds it as if it's present. How is the error fitting in? Also, is that right? I would imagine something more like:
`!targetExists && ((SkipNonexistentTargets && !entry.Request.Targets.Contains(targetName)) || (SkipNonexistentTopLevelTargets && entry.Request.Targets.Contains(targetName)))`
Otherwise, it's skipping when you have a nonentry target but set SkipNonexistentTopLevelTargets.

Also, as a nit, [HasFlag is slow](https://stackoverflow.com/questions/7368652/what-is-it-that-makes-enum-hasflag-so-slow). Not that big a deal, but I thought I should mention it.

**Comment by jeffkl** [comment]
@Forgind I've updated the PR to address the issue you pointed out and added a unit test for it as well.  I'm going to leave `HasFlag` in for now since its adding to an existing one, but I do think we should ban it in the repo.

**Review by Forgind — APPROVED** [review]
Looks good! I tried to think of cases in which this would fail but didn't come up with any, and your explanation helped me properly understand that if clause. Thanks!

**Review by KirillOsenkov — APPROVED** [review]

**Pull request merged**
