### PR TITLE
Adding dummy GenerateSupportedTargetFrameworkAlias target

### PR DESCRIPTION
**Pull request by sfoslund**

### CODE REVIEW

**Comment by Forgind** [comment]
This is for your work with Project System? Are you planning to call this in the SDK and override the default in PS?

**Comment by sfoslund** [comment]
Yup, other way around. It's being overridden in the SDK [here](https://github.com/dotnet/sdk/pull/13795) and the project system is calling it. We need a stub in MSBuild because the target needs to always exist otherwise we'll get an error when a user targets an old SDK using global.json that doesn't have this target.

**Review by Forgind — APPROVED** [review]
Sounds good. Approved.

**Review by dsplaisted — APPROVED** [review]

**Review by melytc — APPROVED** [review]

**Comment by sfoslund** [comment]
@rainersigwald, @marcpopMSFT and I discussed this offline and I'm merging since we're close to locking down. Let me know if you have any comments, thanks!

**Comment by Forgind** [comment]
I didn't notice this, but since master is still 16.8, please don't use vs16.8 yet.

**Pull request merged**
