### PR TITLE
Add a comment to all sources under src/Deprecated

### PR DESCRIPTION
**Pull request by ladipro**
### Context

I regularly find myself making changes to files without realizing they are in the deprecated part of the tree. Having a clear "you're not supposed to be here" indicator would save me time.

### Changes Made

Added a comment to all C# files under src/Deprecated. This should help in cases when the developer opens the file by name (e.g. using a GoToFile IDE functionality).

### Testing

`git diff --stat` to make sure all files got exactly +4 lines.

### Notes

- The change was made with a script that preserves the BOM in the files.
- The comment is a minor rewording of `src/Deprecated/README.md`.
- I sometimes get to these files using FindInFiles IDE functionality which immediately scrolls the file to the hit line so this comment won't help.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]
No objection here. I did a few spot-checks and all the changes look good to me.

Can you share the script you used for posterity?

**Comment by ladipro** [comment]
Here it is, quick and dirty:

```C#
using System.Diagnostics;
using System.Text;

string[] linesToAdd =
{
    "// THE ASSEMBLY BUILT FROM THIS SOURCE FILE HAS BEEN DEPRECATED FOR YEARS. IT IS BUILT ONLY TO PROVIDE",
    "// BACKWARD COMPATIBILITY FOR API USERS WHO HAVE NOT YET MOVED TO UPDATED APIS. PLEASE DO NOT SEND PULL",
    "// REQUESTS THAT CHANGE THIS FILE WITHOUT FIRST CHECKING WITH THE MAINTAINERS THAT THE FIX IS REQUIRED."
};

if (args.Length != 1)
{
    Console.WriteLine($"Usage: {Process.GetCurrentProcess().ProcessName} <directory>");
    return;
}

foreach (var file in Directory.GetFiles(args[0], "*.cs", SearchOption.AllDirectories))
{
    var tmpFile = file + ".tmp";
    TransformFile(file, tmpFile, linesToAdd);

    File.Delete(file);
    File.Move(tmpFile, file);
}

// From https://stackoverflow.com/questions/3825390/effective-way-to-find-any-files-encoding
static Encoding GetEncoding(string filename)
{
    // Read the BOM
    var bom = new byte[4];
    using (var file = new FileStream(filename, FileMode.Open, FileAccess.Read))
    {
        file.Read(bom, 0, 4);
    }

    // Analyze the BOM
    if (bom[0] == 0x2b && bom[1] == 0x2f && bom[2] == 0x76) return Encoding.UTF7;
    if (bom[0] == 0xef && bom[1] == 0xbb && bom[2] == 0xbf) return Encoding.UTF8;
    if (bom[0] == 0xff && bom[1] == 0xfe && bom[2] == 0 && bom[3] == 0) return Encoding.UTF32; //UTF-32LE
    if (bom[0] == 0xff && bom[1] == 0xfe) return Encoding.Unicode; //UTF-16LE
    if (bom[0] == 0xfe && bom[1] == 0xff) return Encoding.BigEndianUnicode; //UTF-16BE
    if (bom[0] == 0 && bom[1] == 0 && bom[2] == 0xfe && bom[3] == 0xff) return new UTF32Encoding(true, true);  //UTF-32BE

    // Assume UTF8 (no BOM) if we reach this point
    return new UTF8Encoding(false);
}

static void TransformFile(string srcFile, string dstFile, string[] linesToAdd)
{
    using StreamReader sr = new StreamReader(srcFile);
    using StreamWriter sw = new StreamWriter(dstFile, true, GetEncoding(srcFile));

    bool readingLeadingComment = true;

    string line;
    while ((line = sr.ReadLine()) != null)
    {
        // Skip the license comment at the top
        if (readingLeadingComment && !line.StartsWith("//"))
        {
            sw.WriteLine();
            foreach (var lineToAdd in linesToAdd)
            {
                sw.WriteLine(lineToAdd);
            }
            readingLeadingComment = false;
        }
        sw.WriteLine(line);
    }
}
```

**Review by vlada-shubina — APPROVED** [review]
Thanks, this is much helpful.

**Review by JanKrivanek — APPROVED** [review]
Thanks!

Perfect PR to smuggle in some hidden vulnerability ;-D So I tried to export the diff and verify it's all just comments - all good! ;-)

**Pull request merged**
