### PR TITLE
SetPlatform: Use Platform Instead Of PlatformTarget

### LINKED ISSUE #6887: ProjectReference Platform Negotiation - Pass Platform Instead of PlatformTarget
### Discussed in https://github.com/dotnet/msbuild/discussions/6871

<div type='discussions-op-text'>

<sup>Originally posted by **jhennessey** September 20, 2021</sup>
I'm trying to make use of the new [ProjectReference SetPlatform Negotiation](https://github.com/dotnet/msbuild/blob/main/documentation/ProjectReference-Protocol.md#setplatform-negotiation) feature. After performing all of the documented steps to enable the feature, I could not get a simplistic two project (non-SDK style) build to work correctly. In this case, **NetFx.Library2** (x86/x64) referenced **NetFx.Library1** (AnyCPU). When attempting to build, it would result with the following error:

`(_CheckForInvalidConfigurationAndPlatform target) ->
  c:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(820
,5): error : The BaseOutputPath/OutputPath property is not set for project 'NetFx.Library1.csproj'.  Please check to ma
ke sure that you have specified a valid combination of Configuration and Platform for this project.  Configuration='Debug'  Platform='x64'.  You may be seeing this message because you are trying to build a project without a solution file,
 and have specified a non-default Configuration or Platform that doesn't exist for this project.`
 
After exploring the logs and associated code changes for the feature, I could see that `PlatformTarget` was being passed to the referenced project [here](https://github.com/dotnet/msbuild/blob/c5eef1eb28e4e3984fd41be6f25f410f698dc126/src/Tasks/Microsoft.Common.CurrentVersion.targets#L1678). That doesn't appease the referenced project because it uses `Platform` for its defined configurations. **However**, if I change the referenced code to pass `Platform` (along with `PlatformTarget`) my build works as expected.

Is there any reason why `Platform` can't also be passed to the referenced projects?

#5338 
#6655

Logs:
[error.log](https://github.com/dotnet/msbuild/files/7197630/error.log)
[success.log](https://github.com/dotnet/msbuild/files/7197631/success.log)
 </div>

### Summarized
The long and the short of it: We should be passing `Platform=` instead of `PlatformTarget=`. There also needs to be an investigation as to whether or not we need to remove the use of `PlatformTarget` within the feature.

### PR DESCRIPTION
**Pull request by BenVillalobos**
Fixes #6887
Discussion: https://github.com/dotnet/msbuild/discussions/6871

### Context
`PlatformTarget `was initially passed to managed projects because `PlatformTarget` is passed directly to the compiler, while Platform is passed to the cpp compiler. After a deeper investigation, it turns out we can pass `Platform` and `PlatformTarget` will be defined either in the project file or by the SDK _based on Platform_.

### Changes Made
Pass and undefine Platform instead of PlatformTarget.

Usage of PlatformTarget has been removed altogether, in favor of Platform.

### Testing
Tested on all projects here: https://github.com/BenVillalobos/setplatform-repro
Also confirmed by jhennessey that this solves the issue.

### CODE REVIEW

**Review by rainersigwald — APPROVED** [review]

**Review by Forgind — APPROVED** [review]

**Comment by BenVillalobos** [comment]
@jhennessey We're trying to get this merged in ASAP. Any way you could try this diff soon and see if this still builds your big ol' project?

**Comment by Forgind** [comment]
[Docs on how to deploy locally](https://github.com/dotnet/msbuild/blob/main/documentation/Deploy-MSBuild.md) if you need it

**Comment by jhennessey** [comment]
> We're trying to get this merged in ASAP. Any way you could try this diff soon and see if this still builds your big ol' project?

@BenVillalobos  - It works! :).

I'll mention that I've been working on a fix locally which I think should be addressed with P2P builds. The issue is that the following combination will fail (assume `Platform=x64` was passed on the command line):

LibraryA [x64] -> LibraryB [AnyCPU] -> LibraryC [x64]

In this case, you'll end up getting the 'BaseOutputPath/OutputPath property is not set error` for LibraryC. Should I file a separate bug for this?

**Comment by BenVillalobos** [comment]
> It works! :).

🥳

> LibraryA [x64] -> LibraryB [AnyCPU] -> LibraryC [x64]
In this case, you'll end up getting the "...BaseOutputPath/OutputPath property is not set..." error for LibraryC. Should I file a separate bug for this?

Yes please! To be clear, the issue you're running into is that B doesn't know what came before it, so it logs a warning and undefines Platform for C, then tells C to build on its own right? I don't know what your project file looks like, but most legacy projects define a default value for Platform when it's not defined, and that value is AnyCPU. Would changing that value for your C project work? (might be best to file the issue and continue the discussion there). The expected workaround for now is to add `SetPlatform` metadata on your project reference. If you assign SetPlatform metadata, the logic to "figure it out" is skipped over. 

 It's currently a known issue, and one that's difficult to fix without implementing some sort of "walk" through every P2P to figure this out ahead of time. It was discussed and put to the side until setplatform version 1 could be merged.

**Comment by AArnott** [comment]
> LibraryA [x64] -> LibraryB [AnyCPU] -> LibraryC [x64]

I would argue that the LibraryB -> LibraryC P2P should not exist. LibraryB cannot be an AnyCPU library when it depends on an x64 binary. In some cases msbuild or csc will emit warnings about a reference like this. When you _really_ want to do it anyway, as @BenVillalobos says, I would expect you to add `SetPlatform` metadata on the `ProjectReference` item directly to make msbuild allow you to do this (without a warning).

**Review by AArnott — APPROVED** [review]

**Pull request merged**
