### PR TITLE
Remove response prefix from ResponseFileUsedEventArgs and derivates

### PR DESCRIPTION
**Pull request by edvilme**
Fixes #

### Context
#8146 added the ability to include used response files in the binlog viewer. However, as noted by @KirillOsenkov, it should be expandable for all kinds of used files (https://github.com/dotnet/msbuild/pull/8146#issuecomment-1353867065), removing the "Response" prefix. 

### Changes Made
- Renamed `ResponseFileUsedEventArgs` to `FileUsedEventArgs`
- Renamed `BinaryLogRecordKind.ResponseFileUsed` to `BinaryLogRecordKind.FileUsed`
- Renamed `LoggingEventType.ResponseFileUsedEvent` to `LoggingEventType.FileUsedEvent`
- Renamed `WriteResponseFileUsedEventToStream` to `WriteFileUsedEventToStream`
- Renamed `ReadResponseFileUsedEventFromStream` to `ReadFileUsedEventFromStream`

### CODE REVIEW

**Comment by edvilme** [comment]
I think this introduces breaking changes, so I am making this a draft PR open to consideration

**Comment by rainersigwald** [comment]
Yes, unfortunately I think we missed the window on this rename since the event types are public and the `ResponseFile` names shipped in 17.5. We can change the doc comments on the types to indicate that they are more generic, though . . .

**Comment by KirillOsenkov** [comment]
Or we could see if a TypeForwardedTo can help here.

But honestly, it's OK to just drop it. YAGNI. Not worth the headache.

**Comment by edvilme** [comment]
Alright. I will close the pr then 😬

**Pull request closed without merging**
