### PR TITLE
Add main as a CI & pipeline trigger

### PR DESCRIPTION
**Pull request by BenVillalobos**
Part of https://github.com/dotnet/msbuild/issues/6249

### Context
Include main as a branch to trigger CI for master -> main transition.

### Changes Made
Add main to CI and pipeline yml files.

### Notes
If you'd like to sanity check (should take ~1 min), see https://github.com/dotnet/arcade/blob/main/Documentation/Projects/M2MRenaming/Master-to-Main-renaming-guide.md#2-add-main-triggers-to-yaml-pipelines

### CODE REVIEW

**Review by rokonec — APPROVED** [review]
Looks OK to me. I expect we will remove 'master' at some point later.

**Comment by BenVillalobos** [comment]
@rokonec Thanks! Yep, keeping master for now is a "just in case" and will be removed later.

**Review by Forgind — APPROVED** [review]
Looks fine. But are you planning to add more to this PR later or make other PRs? And I'm assuming there's a good bit of work on the AzDO side.

**Comment by BenVillalobos** [comment]
@Forgind This PR will be inserted as soon at CI passes. There may be another PR later that changes any required updates to references of `msbuild/master` in this repo (at the moment I'm not aware of any other than documentation, which I believe will automatically forward to the appropriate `main` branch), and another PR that will remove `master` as a trigger entirely once we know we're okay.

**Pull request merged**
