### PR TITLE
Fix MakeRelative regression intrdouced in msbuild shipped with VS16.10

### LINKED ISSUE #6493: $([MSBuild]::MakeRelative()) returns different values on 16.10 than older version
### Issue Description
Newest version of VisualStudio (MSBuild 16.10) return different values on msbuild property function MakeRelative() with paths ending backslash.

### Steps to Reproduce
code: $([MSBuild]::MakeRelative('c:\windows\\', 'c:\windows\system32\\'))
MSBuild 16.10 returns:  'system32'
MSBuild 16.9 and older returns: 'system32\\'

### Expected Behavior
according to https://docs.microsoft.com/en-us/dotnet/api/system.uri.makerelativeuri?view=net-5.0
it should returns 'system32\\'

### Actual Behavior
returns 'system32'

### Analysis
MSBuild unittests does not contains paths ending backslash
https://github.com/dotnet/msbuild/blob/main/src/Shared/UnitTests/FileUtilities_Tests.cs#L86

### Versions & Configurations
16.10.0.26302

### PR DESCRIPTION
**Pull request by pmisik**
Fixes #6493

### Testing
Added missing directory related unittests

### CODE REVIEW

**Comment by rainersigwald** [comment]
Can you rebase this off the `vs16.10` branch so we can (potentially, not promising yet) take it for a patch release of 16.10?

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6504) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6504) before we can accept your contribution.<br/><br/>:x: pmisik [sign now](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6504)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/msbuild?pullRequest=6504) it.</sub>

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6504) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6504) before we can accept your contribution.<br/><br/>:x: pmisik [sign now](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6504)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/msbuild?pullRequest=6504) it.</sub>

**Comment by pmisik** [comment]
> 
> 
> Can you rebase this off the `vs16.10` branch so we can (potentially, not promising yet) take it for a patch release of 16.10?

I'll do it if after it pass CI.
First step was to break unittests (as directory related unittests were missing) to prove it has broken previous MSBuild.
Second commit is fix  based on @dsparkplug  analysis.
I hope it will fix it.
Unfortunately I cannot run it locally on my machine as I see 
`Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0.  Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.`

**Comment by rainersigwald** [comment]
> Unfortunately I cannot run it locally on my machine as I see
> `Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.TargetFrameworkInference.targets(141,5): error NETSDK1045: The current .NET SDK does not support targeting .NET 6.0. Either target .NET 5.0 or lower, or use a version of the .NET SDK that supports .NET 6.0.`

To fix that, either rebase (to get back to a branch that targets .NET 5.0), or install the latest .NET 6.0 preview SDK. I recommend the former :)

**Comment by dsparkplug** [comment]
While this patch will fix the issue with directories, a directory separator will be added to the end of the output for all input, causing the existing unit tests for files to fail. A solution would need to check whether `path` is a file.

**Comment by dsparkplug** [comment]
Added a new pull request to replace this one #6508

**Comment by pmisik** [comment]
> Can you rebase this off the `vs16.10` branch so we can (potentially, not promising yet) take it for a patch release of 16.10?

I've rebased and squashed (to me intermediate commit are useless - single commits on production branches are better to find cause of issue) work to be potentially applied on 16.10 branch.
I vote for fix in VS16.10.
For company I work at this is blocker bug (we have many supported target branches with different vc toolsets).
Unfortunately, there is no support in VS2019 to have multiple msbuild versions side by side for various VC toolsets (the same issue applies on WDK - as it overwrites original one build sub-directory :-( ). 
So, if any developer at company install VS 16.10 it will break all existing branches development for him.

Should it be as new feature request for VS2022 to have support side by side msbuild suppport?

After squash I amended commit message to be explicitly visible all credits to this fix belongs to @dsparkplug
Author and committer should belongs to @dsparkplug.
Mine only intentions is to be fixed this issue ASAP in production.

**Comment by rainersigwald** [comment]
> I vote for fix in VS16.10.
> For company I work at this is blocker bug (we have many supported target branches with different vc toolsets).
> Unfortunately, there is no support in VS2019 to have multiple msbuild versions side by side for various VC toolsets (the same issue applies on WDK - as it overwrites original one build sub-directory :-( ).
> So, if any developer at company install VS 16.10 it will break all existing branches development for him.

Thanks for this--this kind of detailed problem description helps us get approval for servicing bugs. We'll let you know the outcome of that process (I'm optimistic).

**Comment by Forgind** [comment]
#6513 had the key change from this PR, so closing as superseded by that. Thanks for the contribution @pmisik!

**Pull request closed without merging**
