### PR TITLE
Reapply Support lazy instantiation of ProjectInstance values when CPS Evaluation cache is used

### PR DESCRIPTION
**Pull request by sgreenmsft**
Fixes AB#2067934

### Context
A previous refactoring for performance optimization introduced a regression in memory usage in vcxprojreader (AB#2067934). Consequently, the new code was reverted until a fix was available. This PR contains the fix and reinstates the performance optimization code.

### Changes Made
- Reapplies commit https://github.com/dotnet/msbuild/commit/eade7200e9e8c3f7017c7eff60b7cf591b2e71ac
- Modifications to avoid regression of additional memory usage in vcxprojreader test scenario (specifically in the handling of enumeration to avoid enumerator allocation).

### Testing
Manual verification of the impacted scenario.

### CODE REVIEW

**Comment by YuliiaKovalova** [comment]
experimental insertion for checking the performance: https://dev.azure.com/devdiv/DevDiv/_git/VS/pullrequest/563920

**Comment by JanKrivanek** [comment]
New exp run: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/567664

**Comment by JanKrivanek** [comment]
And yet another exp insertion: https://devdiv.visualstudio.com/DevDiv/_git/VS/pullrequest/567802 (as there were couple failed perf tests in previous that seems as noise to me - comparing to variance of previous main builds)

**Review by JanKrivanek — APPROVED** [review]
I'm fine with the change:
* For the actual changes I defer to previous reviews (on https://github.com/dotnet/msbuild/pull/10030)
* All 3 VS insertions haven't showed statistically significant degradation of perf in measured scenarios (there were some cases within variations - non of which showed on more than 1 run).

**Review by rainersigwald — APPROVED** [review]
Fine by me if insertions are in good shape so we can isolate any regression this does cause.

**Pull request merged**
