### PR TITLE
Fix dotnet/msbuild#2927: changes for Microsoft.Build.Engine

### LINKED ISSUE #2927: Fix XML documentation warnings
When generating XML documentation, a bunch of warnings are produced, ie CS1570, CS1572, CS1573, and CS1587.

I am disabling these warnings but ideally we should fix the underlying issues with the XML docs.

### PR DESCRIPTION
**Pull request by jrdodds**
Fixes #2927

### Context
XML Doc comments changes for Microsoft.Build.Engine and Microsoft.Build.Conversion

### Changes Made
Resolve warnings 1570;1572;1573

### Testing
Remove warning suppression and build. Check that no warnings are reported.

### Notes
I expect to make two initial commits for this pull request. One commit each for the Microsoft.Build.Engine and Microsoft.Build.Conversion projects.

### CODE REVIEW

**Review by Forgind — APPROVED** [review]

**Comment by rainersigwald** [comment]
I don't think we should take these refactoring tweaks to long-deprecated code, but it looks like you asked for them in https://github.com/dotnet/msbuild/issues/2927#issuecomment-828497698, @Forgind. What's the motivation there?

**Comment by jrdodds** [comment]
> I don't think we should take these refactoring tweaks to long-deprecated code, but it looks like you asked for them in [#2927 (comment)](https://github.com/dotnet/msbuild/issues/2927#issuecomment-828497698), @Forgind. What's the motivation there?

@rainersigwald @Forgind If it helps, please note that all the changes that are in .cs files, are comment changes only. No actual code was changed or refactored. The project files were changed only for the `NoWarn` configuration. Thanks

**Comment by Forgind** [comment]
I don't think there was a serious motivation. mfkl made the changes to non-deprecated code, and we didn't immediately close it because the issue wasn't technically fully resolved, but we honestly probably should've; there wasn't any more value to add. I probably just answered the question without thinking about whether it was something we really wanted. I don't think this change will hurt anything, and it looks like it was done properly, so I approved, but I think it very reasonable to not take this and close that issue.

**Comment by jrdodds** [comment]
Issue has been closed.

**Pull request closed without merging**
