### PR TITLE
.NET 8 RC2

### PR DESCRIPTION
**Pull request by rainersigwald**
Move to newest release.

### CODE REVIEW

**Comment by rainersigwald** [comment]
Needs #9319.

**Review by JanKrivanek — APPROVED** [review]

**Comment by marcpopMSFT** [comment]
> Ah interesting, since the SDK now requires 17.8 we have to wait until that ships and is available to our official and PR build machines. @marcpopMSFT, did the policy on that change? I expected 8.0.100 GA to require 17.7.

The GA requires 17.7 to target 7 and below. We've always required the matching VS version to target the releasing runtime. See this super confusing table for more details: https://learn.microsoft.com/en-us/dotnet/core/porting/versioning-sdk-msbuild-vs#targeting-and-support-rules

**Comment by rainersigwald** [comment]
We'll just wait for GA.

**Pull request closed without merging**
