### PR TITLE
Revert "Onboarding to V3 publishing "

### PR DESCRIPTION
**Pull request by epananth**
Reverts dotnet/msbuild#6052

Going to revert this change, as the change is making the build flaky.

### CODE REVIEW

**Comment by BenVillalobos** [comment]
So our pipeline builds should work (🤞) when this and https://github.com/dotnet/arcade/pull/6840 are merged in? Any other changes required?

**Comment by epananth** [comment]
I am going to make the change in m-build, so you don't have to wait for arcade update.. You will be unblocked as soon as the other PR merges..

**Comment by BenVillalobos** [comment]
Gotcha, clarifying for others here:

The linked arcade PR was merged, normally we'd have to wait for an automated "arcade update" PR to take the changes. Instead, we're going to merge this PR then create that automated PR ourselves to get us unblocked.

Eventually we'll get the automated arcade update and we'll merge that in to be back in sync.

**Review by BenVillalobos — APPROVED** [review]

**Comment by BenVillalobos** [comment]
This is blocked on getting a successful optprof run for MSBuild, which is blocked on applying a new azure subscription for our optprof collection release. Our previous subscription was invalidated just in time for this 😮

**Comment by epananth** [comment]
what do you suggest? so I cannot merge this, and the build won't be successful till I get my post-build fix

**Comment by BenVillalobos** [comment]
@epananth For now I'd suggest prepping the next PR so that when we do get a solid optprof run we can merge the two quickly. Until then, I guess MSBuild just has to wait until that subscription gets renewed. I've tried about 7 different ways to trick our builds into using some other optprof data to no avail ¯\_(ツ)_/¯

**Comment by epananth** [comment]
If we have to wait, msbuild will get an arcade update on Monday anyway.

**Pull request merged**
