### PR TITLE
Loc updates

### PR DESCRIPTION
**Pull request by cristianosuzuki77**
Latest translations.

### CODE REVIEW

**Review by Forgind — APPROVED** [review]

**Review by BenVillalobos — APPROVED** [review]

**Comment by wli3** [comment]
@Forgind @BenVillalobos merge?

**Comment by BenVillalobos** [comment]
@wli3 our branch is still locked down until we can get latest/master inserted. It should be unblocked soon.

**Comment by BenVillalobos** [comment]
I see this is targeting 16.9. We should target master for this when we merge.

**Comment by wli3** [comment]
@BenVillalobos in the end this need to be inserted to VS16.9 before the last insertion. So which branch this should target? And how long do we need to wait?

**Comment by BenVillalobos** [comment]
@wli3 you're right. We should _actually_ merge this into vs16.9 and let automation create a vs16.9 -> master PR for us. I'll merge this and make sure it gets a proper pipeline build (optprof is still giving us trouble).

**Pull request merged**
