### PR TITLE
⬆ Update a bunch of package references

### PR DESCRIPTION
**Pull request by rainersigwald**
Update a ton of our package references to the latest available version.

I recommend going commit-by-commit on this one.

### CODE REVIEW

**Comment by Forgind** [comment]
I'm not at all opposed to this, but would you mind throwing it in an exp branch (or I can if you'd prefer)? I have a feeling this will cause ngen problems, and if so, it would be good to know what to do before merging.

**Comment by rainersigwald** [comment]
VS insertions are blocked on a bunch of upgrades there, but I think dotnet/roslyn#49789 and its linked VS pr will take care of a bunch of that (so thanks, @AArnott!).

**Comment by AArnott** [comment]
@rainersigwald You are updating some packages that I didn't look at in the VS repo. So if you're taking those dependencies in the devenv.exe process, we may need to update more platform DLLs for this to work.

**Comment by Forgind** [comment]
Since it's been almost 7 months, have the platform DLLs AArnott mentioned been updated? If so, other than conflicts, is there anything we need before this can go in?

**Comment by rainersigwald** [comment]
No, they haven't. Who knows when we'll get back to this so let's just get rid of it.

**Pull request closed without merging**
