### PR TITLE
Merge NullReferenceException property function evaluation fix to 16.11

### LINKED ISSUE #6413: NullReferenceException in SpanBasedConcatenator when evaluating target dependencies
Seeing this exception when building a project:

```
MSBUILD : error MSB1025: An internal failure occurred while running MSBuild.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Evaluation.Expander`2.SpanBasedConcatenator.Add(Object obj)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)
   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)
   at Microsoft.Build.BackEnd.TargetEntry.GetDependencies(ProjectLoggingContext projectLoggingContext)
   at Microsoft.Build.BackEnd.TargetBuilder.<ProcessTargetStack>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.TargetBuilder.<BuildTargets>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildProject>d__67.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Build.BackEnd.RequestBuilder.<BuildAndReport>d__58.MoveNext()
```

It does *not* repro with `16.9.0+5e4b48a27` but does with `16.10.0-preview-21181-05+80f316e90` and `16.10.0-preview-21227-06+1d1fec7c4`.

I'll try to get a minimal repro, but this is happening in a private repo I'm not very familiar with. Ping me on Teams for instructions cloning the repo this is happening to in the meantime.

### PR DESCRIPTION
**Pull request by ladipro**
Fixes #6413

### Context

The fix has been merged into 16.10. Automation has opened a PR to merge into main. This PR takes care of porting to 16.11.

### Changes Made

Merged #c040391f9affa509a9a879e17b5d2994ee585a52.

### Testing

Unit tests.

### CODE REVIEW

**Comment by rainersigwald** [comment]
LGTM; should we bother setting up automation for this? We'll have at minimum the loc and final-branding PRs going into 16.10 and any other late fixes.

**Comment by ladipro** [comment]
Would be safer to have these ports automated, for sure. How difficult is it to set it up?

**Comment by rainersigwald** [comment]
It's a PR to the file that controls the relationship: https://github.com/dotnet/versions/blob/12e51a28f75094d793e2bc43fb76b6784346fa9a/Maestro/subscriptions.json#L1179-L1195

Should be quite straightforward, the only wrinkle being that we might want to disable the 16.10->main flow and go 16.10->16.11->main to avoid extra commits. but I don't feel that strongly about it since I think that's nontrivial (we currently do `16*->main`).

**Comment by ladipro** [comment]
Created a PR to go 16.10->16.11->main: https://github.com/dotnet/versions/pull/756

**Review by Forgind — APPROVED** [review]

**Comment by Forgind** [comment]
> (we currently do `16*->main`).

Can we add vs17* as well?

**Comment by rainersigwald** [comment]
Superseded by #6439.

**Pull request closed without merging**
