### PR TITLE
Bump some System.* deps to 8.0.0

### PR DESCRIPTION
**Pull request by rainersigwald**
While looking at something else, I noticed that these references were stale.

(This should be automated but https://github.com/dependabot/dependabot-core/issues/7206.)

### CODE REVIEW

**Review by rokonec — APPROVED** [review]

**Review by YuliiaKovalova — APPROVED** [review]

**Comment by AraHaan** [comment]
At this point why not have the .NET github bot update these here as well?

**Review by AraHaan — COMMENTED** [review]
LGTM (Also why not bump all of the System.* deps?)

**Comment by rainersigwald** [comment]
> At this point why not have the .NET github bot update these here as well?

There's no mechanism for "latest released version of this package" in the darc/maestro system. Since we need to depend on stable versions that match the ones in Visual Studio, we can't generally go to "the latest from a particular channel" like most of .NET can.

> Also why not bump all of the System.* deps?

Did I miss something?

**Review by MichaelSimons — APPROVED** [review]

**Comment by AraHaan** [comment]
> > At this point why not have the .NET github bot update these here as well?
> 
> There's no mechanism for "latest released version of this package" in the darc/maestro system. Since we need to depend on stable versions that match the ones in Visual Studio, we can't generally go to "the latest from a particular channel" like most of .NET can.
> 
> > Also why not bump all of the System.* deps?
> 
> Did I miss something?

- System.Private.Uri
- System.Runtime
- System.Security.Cryptography.X509Certificates

Are among the ones I see. I think it should be safe to update these too if available.

**Comment by rainersigwald** [comment]
> > > At this point why not have the .NET github bot update these here as well?
> > 
> > 
> > There's no mechanism for "latest released version of this package" in the darc/maestro system. Since we need to depend on stable versions that match the ones in Visual Studio, we can't generally go to "the latest from a particular channel" like most of .NET can.
> > > Also why not bump all of the System.* deps?
> > 
> > 
> > Did I miss something?
> 
> * System.Private.Uri
> * System.Runtime
> * System.Security.Cryptography.X509Certificates
> 
> Are among the ones I see. I think it should be safe to update these too if available.

"if available" is the key phrase. Those all look like latest to me:

https://www.nuget.org/packages/System.Private.Uri#versions-body-tab
https://www.nuget.org/packages/System.Runtime#versions-body-tab
https://www.nuget.org/packages/System.Security.Cryptography.X509Certificates#versions-body-tab

**Pull request merged**
