### PR TITLE
Restore newline auto return

### LINKED ISSUE #8008: Breaking change in linebreak handling in 7.0 RC1
### Description

I'm unsure if this is an issue in `dotnet run` or in the underlying runtime/libraries, so please redirect elsewhere if needed. Also, I don't know if this is a deliberate change.

### Customer impact

The impact of this change is that existing code that renders to the console produces corrupt output. It seems to be that, in the past, a Unix-style `\n` was enough to produce normal newline behaviors, whereas this has changed and now it only works on Windows if you output `\r\n`. Our cross-platform compatibility has been reduced.

### Reproduction Steps

1. Create a new console app (`dotnet new console`)
2. Change the contents of `Program.cs` to be `Console.WriteLine("Line1\nLine2");`
3. Run it on Windows in either the *Terminal* app or the old-school console (i.e., `cmd.exe`) using the command `dotnet run`

### Expected behavior

In 7.0 preview 7 (I tried 7.0.100-preview.7.22377.5) and earlier, the output is:

```
Line1
Line2
```

This is the expected and desired output

### Actual behavior

Starting from 7.0 RC1 and still happening with RC2 builds, you get:

```
Line1
     Line2
```

### Regression?

Yes, worked in 7.0.100-preview.7.22377.5

### Known Workarounds

None

### Configuration

Windows 11 x64
Works in 7.0.100-preview.7.22377.5
Fails in 7.0.100-rc.1.22431.12 and 7.0.100-rc.2.22463.6

### Other information

_No response_

### PR DESCRIPTION
**Pull request by Forgind**
Fixes #8008

### Context
With the MSBuild server, I added support for VT100, which meant we could understand colorization and such from an older command prompt, but I also added DISABLE_NEWLINE_AUTO_RETURN, which made the UI look worse.

### Customer Impact
Customers using MSBuild server  and trying to print newlines (`\n`) will see output with extra space.

### Testing
Manually tested the change: ran the proposed repro project and saw the bug. Overwrote the MSBuild in that SDK with custom bits from this PR and retested it, and I could no longer reproduce the issue. Tried using MSBuild.exe on a random project, and the important part of the VT100 change was preserved.

### Code Reviewers
rokonec

### Description of fix
Removed the DISABLE_NEWLINE_AUTO_RETURN argument

### CODE REVIEW

**Comment by rainersigwald** [comment]
The bug mentioned an alternate solution strategy, which was "replace the mode at the end of the build". Did you consider and discard that? Is this a better option?

**Comment by Forgind** [comment]
I was the one who first noticed the VT100 issue because I use cmd for most things. I typically believe the simplest solution that resolves the problem is the best solution, as it is least likely to have hidden bugs, and this simplifies the code rather than potentially leaving some issue open with a build that fails to reset the mode after some unusual sequence of events. I tested that this did not reintroduce the issue I'd seen by building something with the bootstrapped MSBuild.exe. If the problem remains resolved, and the code is simpler, I think it is the best solution.

**Review by rokonec — APPROVED** [review]
Looks legit. What was the intent behind disabling it originally?

**Comment by Forgind** [comment]
> Looks legit. What was the intent behind disabling it originally?

As I recall, I found code that claimed to resolve the VT100 issue. I put it into MSBuild and tried testing it, and it seemed to work properly whether or not that parameter was present. Since whoever wrote the snippet I'd found online seemed to think it was important, I figured there was some case I hadn't tested where it would be useful, so I left it in.

**Comment by rainersigwald** [comment]
Does leaving `ENABLE_VIRTUAL_TERMINAL_PROCESSING` on have no cost to subsequent CLI interactions or user programs in `dotnet run`? Wouldn't it mask the need to set that in the actual application if it emits VT100 codes?

**Comment by rainersigwald** [comment]
For instance, is this behavior difference acceptable, even if we fix the newline situation?

image

**Comment by Forgind** [comment]
For clarity, is your concern that it converted `\x1b[31m` into "change the color to red"? Honestly, I don't know why someone would want to see `\x1b[31m`.

But cc @baronfel for a proper opinion.

**Comment by rainersigwald** [comment]
Yes, that's the concern. It's possible that it's explicitly outputting that for Reasons, but I would say my concern runs the other way: if you run it with `dotnet run` and it always renders the VT100 codes instead of spewing console gibberish, you'll likely be surprised when the deployed app instead spews gibberish.

**Comment by baronfel** [comment]
Correct - @rainersigwald has the scenario nailed here. MSBuild should return the state to whatever it was before invoking MSBuild. Other applications shouldn't have to alter their behavior based on whether or not they were run after MSBuild in a `dotnet run` scenario.

**Comment by Forgind** [comment]
Ok, that's more reasonable than wanting random codes in your output. I'd suggest that's perpendicular to this change, as this change is specifically for newline and (in my opinion) should happen regardless. I can try to put something together to resolve that issue as well.

**Review by rokonec — APPROVED** [review]

**Pull request merged**
