### PR TITLE
[release/vs17.8]  Onboard 1es templates 

### PR DESCRIPTION
**Pull request by surayya-MS**
### Test run

https://dev.azure.com/devdiv/DevDiv/_build/results?buildId=9463950&view=results

### CODE REVIEW

**Review by YuliiaKovalova — APPROVED** [review]

**Comment by rainersigwald** [comment]
I would expect a 17.7->17.8 merge to be the way to do this. Is that not a good option?

**Comment by surayya-MS** [comment]
> I would expect a 17.7->17.8 merge to be the way to do this. Is that not a good option?

There were changes from https://github.com/dotnet/msbuild/pull/10042 that we don't want in 17.8 I believe. @JanKrivanek correct me please

**Comment by JanKrivanek** [comment]
It seems that 17.7 -> 17.8 codeflow was not accepted/merged for couple changes in a row: https://github.com/dotnet/msbuild/pulls?q=is%3Apr+%27vs17.7%27+%3D%3E+%27vs17.8+is%3Aclosed, so I suggested not to use the flow (as it had huge amount of untrelated changes) and do that manually.

Though - we still should backport #10024 manually

**Comment by surayya-MS** [comment]
closing this PR in favor of https://github.com/dotnet/msbuild/pull/10056

**Pull request closed without merging**
