### PR TITLE
Do not run analyzers for XamlPreCompile.

### PR DESCRIPTION
**Pull request by jlaanstra**
Fixes https://github.com/dotnet/sdk/issues/17890; fixes https://github.com/dotnet/roslyn/issues/54774

### Context
#6096 updated the ```XamlPreCompile``` target to be up to date with Roslyn to make sure source generators work for this target as well. However, it also enabled analyzers to run even though none of the targets such as ```CoreGenerateAssemblyInfo``` or ```_ComputeSkipAnalyzers``` are setup correctly to also run before ```XamlPreCompile```.

### Changes Made
This PR reverts parts of #6096 by setting SkipAnalyzers to true for the ```XamlPreCompile``` target but still pass in Analyzers so source generators continue to work.

### Testing
Verified that warnings from mentioned issues go away.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6676) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6676) before we can accept your contribution.<br/><br/>:x: jlaanstra [sign now](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6676)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/msbuild?pullRequest=6676) it.</sub>

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6676) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6676) before we can accept your contribution.<br/><br/>:x: jlaanstra [sign now](https://cla.dotnetfoundation.org/dotnet/msbuild?pullRequest=6676)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/msbuild?pullRequest=6676) it.</sub>

**Comment by chsienki** [comment]
Setting `SkipAnalyzers` to true in this case seems fine to me. Will let the MSBuild folks chime in on the whitespace changes.

**Comment by jlaanstra** [comment]
I can revert the whitespace changes if these are not desired.

**Review by rainersigwald — APPROVED** [review]
If this understanding is correct I'm happy:

1. Analyzers + generators were turned off for perf before.
2. That broke projects with source generators.
3. So we turned them back on with #6096.
4. But then perf suffers again.
5. So this turns off just analyzers and not generators.

I don't feel strongly about the spacing, no need to go back and "fix" it.

**Comment by jlaanstra** [comment]
@rainersigwald I believe that understanding is correct.

**Comment by jlaanstra** [comment]
Anything else needed to merge?

**Review by Forgind — APPROVED** [review]

**Comment by jlaanstra** [comment]
@ladipro @rainersigwald can this be added to the v16.11 branch?

**Comment by azchohfi** [comment]
Just pinging here, and reinforcing @jlaanstra's question. It would be nice to have this still in 16.x.

**Comment by Forgind** [comment]
I think there was an internal email chain at some point that concluded that we weren't going to backport this. Do you have a good reason we should?

**Pull request merged**
