### PR TITLE
Replace MSBuild.Dev.sln and MSBuild.SourceBuild.sln with solution filters

### PR DESCRIPTION
**Pull request by ladipro**
Trivially replaced the two .sln's, which are a strict subset of MSBuild.sln, with .slnf's for easier maintenance.

Source build will likely need to be tweaked to build the new file.

### CODE REVIEW

**Comment by rainersigwald** [comment]
For `MSBuild.Dev.sln` I'm completely on board. For sourcebuild, I'm worried that the version of MSBuild that we use to build ourselves in the initial run isn't new enough to support a solution filter. @dagood, do you know offhand what version that is?

**Comment by dagood** [comment]
I don't know how recently solutions filters got in, but for context, source-build doesn't actually have to build a new version using a *significantly* older version. We'll build source-build 6.0.100 with a prebuilt copy of 6.0.100, then 6.0.101 builds using 6.0.100. Eventually we hope to be able to build e.g. 6.0.200 using 6.0.1XX (depends on having good enough infra for it to be feasible to maintain multiple feature bands), but that's the biggest type of gap we'd like people to keep in mind for now.

**Comment by rainersigwald** [comment]
Ah, great! MSBuild's solution filter support was in 5.0.100 so we should be good.

**Review by rainersigwald — APPROVED** [review]

**Review by Forgind — APPROVED** [review]
LGTM! Thanks!

**Comment by ladipro** [comment]
Created https://github.com/dotnet/source-build/pull/1965 to consume this change in source-build.

**Pull request merged**
