### PR TITLE
Disable localization vs17.9

### PR DESCRIPTION
**Pull request by YuliiaKovalova**
Disable localization vs17.9

### CODE REVIEW

**Comment by rainersigwald** [comment]
Is this necessary? I wouldn't expect it to ever actually do anything . . .

**Comment by YuliiaKovalova** [comment]
> Is this necessary? I wouldn't expect it to ever actually do anything . . .

Let's exclude it from checklist then :)
https://github.com/dotnet/msbuild/issues/9914#:~:text=EnableReleaseOneLocBuild%20to%20true-,Disable,-17.9%20localization%20%2D%20by

**Comment by rainersigwald** [comment]
Oh to be clear I can _definitely_ be misunderstanding things here, we should chase down whoever added that step and confirm!

**Comment by JanKrivanek** [comment]
We localize main and latest release branch (that's the max we can have). Each branch is required to have a separate loc setup, which should not be invoked from a different branch (then we'd get conflicting PRs as we used to have some time back).

For this reason we need to disable the latest release branch localization requests on a new branch creation and issue loc ticket to request swap from (latest-1) to latest.

Alternatively we can localize main only - then we'd need to only disable the latest release branch loc requests (this PR) and we'd avoid the loc tickets. But we'd need to keep in mind to manually temporarily reroute localization on servicing involving resource files changes (as we already now should with older branches servicing - but that rarely happens)

**Review by JanKrivanek — APPROVED** [review]

**Comment by rainersigwald** [comment]
Ok, given the cost of changes to servicing branches (having to bump the version manually) I don't love this--maybe we should invest in version bump automation.

**Review by ladipro — APPROVED** [review]

**Comment by JanKrivanek** [comment]
> Ok, given the cost of changes to servicing branches (having to bump the version manually) I don't love this--maybe we should invest in version bump automation.

https://github.com/dotnet/msbuild/issues/9960

**Pull request merged**
