### PR TITLE
Generate SBOM for msbuild 

### PR DESCRIPTION
**Pull request by epananth**
Fixes #
Generation of SBOM for msbuild
Test: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6597691&view=results

### CODE REVIEW

**Review by Forgind — DISMISSED** [review]
Isn't this identical to https://github.com/dotnet/msbuild/pull/7826?

**Comment by epananth** [comment]
didnt we revert that change, (sorry I opened so many PRs)

**Comment by Forgind** [comment]
Yes; we did.

As I understand the current situation, we need https://github.com/dotnet/arcade/pull/10137, and then we can just do the `/p:GenerateSbom=true` part. I don't think there's anything blocking us from taking that, but we changed our darc subscription to point at 7.0 arcade, which promptly started failing tests, and we haven't gotten it in.

@BenVillalobos (kitten), can you do a one-off insertion of current Arcade release/6.0 into MSBuild, then ping here?

**Comment by epananth** [comment]
Going to close this PR. I only checked your builds not the PRs

**Comment by epananth** [comment]
Closed this too soon :/

**Comment by epananth** [comment]
will keep this open for you to decide. Just letting you know that it works :)

**Comment by BenVillalobos** [comment]
My to-do list here (correct if wrong):
1. Merge https://github.com/dotnet/msbuild/pull/7916
2. Merge this
3. 🤞

**Comment by Forgind** [comment]
I requested changes on this because it should not go in as-is. Once you've merged #7916, we should undo the global.json change before merging this. Upgrading to arcade 7 would be nice, but that's unrelated to this.

**Review by BenVillalobos — APPROVED** [review]

**Comment by epananth** [comment]
I do not have permission to merge this PR. Can anyone merge this pls?

**Comment by BenVillalobos** [comment]
@Forgind merging is blocked on requested changes that have been resolved

**Pull request merged**
